In [1]:
# Verify the existing frozen Derm7pt dataset before external evaluation

import os
import pandas as pd

DERM7PT_ROOT = (
    "/kaggle/input/datasets/akansha1009/"
    "derm7pt-frozen-dataset"
)

DERM7PT_IMAGE_ROOT = os.path.join(
    DERM7PT_ROOT,
    "Derm7pt_Kaggle_Ready",
    "images"
)

DERM7PT_METADATA_PATH = os.path.join(
    DERM7PT_ROOT,
    "Derm7pt_split_metadata.csv"
)

print("DERM7PT FROZEN DATASET VERIFICATION")

print(f"Dataset root exists: {os.path.exists(DERM7PT_ROOT)}")
print(f"Image directory exists: {os.path.exists(DERM7PT_IMAGE_ROOT)}")
print(f"Metadata exists: {os.path.exists(DERM7PT_METADATA_PATH)}")

derm7pt_metadata = pd.read_csv(
    DERM7PT_METADATA_PATH
)

print("\nMetadata shape:")
print(derm7pt_metadata.shape)

print("\nMetadata columns:")
print(derm7pt_metadata.columns.tolist())

print("\nFirst 5 rows:")
display(derm7pt_metadata.head())

print("VERIFICATION COMPLETE")

DERM7PT FROZEN DATASET VERIFICATION
Dataset root exists: True
Image directory exists: True
Metadata exists: True

Metadata shape:
(1011, 9)

Metadata columns:
['case_num', 'diagnosis', 'binary_label', 'label', 'clinic', 'derm', 'split', 'clinic_path', 'derm_path']

First 5 rows:

,case_num,diagnosis,binary_label,label,clinic,derm,split,clinic_path,derm_path
0,1,basal cell carcinoma,Non-Melanoma,0,NEL/NEL025.JPG,NEL/Nel026.jpg,train,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
1,2,basal cell carcinoma,Non-Melanoma,0,NEL/NEL027.JPG,NEL/Nel028.jpg,validation,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
2,3,basal cell carcinoma,Non-Melanoma,0,NEL/Nel032.jpg,NEL/Nel033.jpg,train,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
3,4,basal cell carcinoma,Non-Melanoma,0,NEL/NEL034.JPG,NEL/Nel035.jpg,test,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
4,5,basal cell carcinoma,Non-Melanoma,0,NEL/NEL036.JPG,NEL/Nel037.jpg,train,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...

VERIFICATION COMPLETE

In [2]:
# Inspect the frozen Derm7pt metadata needed for external evaluation

print("Metadata shape:", derm7pt_metadata.shape)

print("\nColumns:")
for column in derm7pt_metadata.columns:
    print(" -", column)

print("\nFirst 10 rows:")
display(derm7pt_metadata.head(10))

print("\nData types:")
print(derm7pt_metadata.dtypes)

print("\nUnique values by column:")
for column in derm7pt_metadata.columns:
    print(f"\n{column}:")
    print(derm7pt_metadata[column].drop_duplicates().tolist()[:20])

Metadata shape: (1011, 9)

Columns:
 - case_num
 - diagnosis
 - binary_label
 - label
 - clinic
 - derm
 - split
 - clinic_path
 - derm_path

First 10 rows:

,case_num,diagnosis,binary_label,label,clinic,derm,split,clinic_path,derm_path
0,1,basal cell carcinoma,Non-Melanoma,0,NEL/NEL025.JPG,NEL/Nel026.jpg,train,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
1,2,basal cell carcinoma,Non-Melanoma,0,NEL/NEL027.JPG,NEL/Nel028.jpg,validation,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
2,3,basal cell carcinoma,Non-Melanoma,0,NEL/Nel032.jpg,NEL/Nel033.jpg,train,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
3,4,basal cell carcinoma,Non-Melanoma,0,NEL/NEL034.JPG,NEL/Nel035.jpg,test,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
4,5,basal cell carcinoma,Non-Melanoma,0,NEL/NEL036.JPG,NEL/Nel037.jpg,train,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
5,6,basal cell carcinoma,Non-Melanoma,0,NEL/Nel038.jpg,NEL/Nel039.jpg,validation,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
6,7,basal cell carcinoma,Non-Melanoma,0,NEL/Nel040.jpg,NEL/Nel041.jpg,test,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
7,8,basal cell carcinoma,Non-Melanoma,0,NEL/Nel084.jpg,NEL/Nel085.jpg,train,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
8,9,basal cell carcinoma,Non-Melanoma,0,NEL/Nel086.jpg,NEL/Nel087.jpg,test,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...
9,10,basal cell carcinoma,Non-Melanoma,0,NEL/NEL088.JPG,NEL/Nel089.jpg,train,/content/drive/MyDrive/Melanoma Skin Lesion An...,/content/drive/MyDrive/Melanoma Skin Lesion An...

Data types:
case_num         int64
diagnosis       object
binary_label    object
label            int64
clinic          object
derm            object
split           object
clinic_path     object
derm_path       object
dtype: object

Unique values by column:

case_num:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

diagnosis:
['basal cell carcinoma', 'blue nevus', 'clark nevus', 'combined nevus', 'congenital nevus', 'dermal nevus', 'dermatofibroma', 'lentigo', 'melanoma (in situ)', 'melanoma (less than 0.76 mm)', 'melanoma (0.76 to 1.5 mm)', 'melanoma (more than 1.5 mm)', 'melanoma metastasis', 'melanosis', 'miscellaneous', 'recurrent nevus', 'reed or spitz nevus', 'seborrheic keratosis', 'vascular lesion', 'melanoma']

binary_label:
['Non-Melanoma', 'Melanoma']

label:
[0, 1]

clinic:
['NEL/NEL025.JPG', 'NEL/NEL027.JPG', 'NEL/Nel032.jpg', 'NEL/NEL034.JPG', 'NEL/NEL036.JPG', 'NEL/Nel038.jpg', 'NEL/Nel040.jpg', 'NEL/Nel084.jpg', 'NEL/Nel086.jpg', 'NEL/NEL088.JPG', 'NEL/NEL090.JPG', 'NEL/NEL093.JPG', 'NEL/Nel094.jpg', 'NEL/NEL096.JPG', 'NEL/NEL099.JPG', 'NEL/Nel101.jpg', 'NFL/Nfl067.jpg', 'NGL/NGL046.JPG', 'NHL/Nhl010.jpg', 'NML/NML097.JPG']

derm:
['NEL/Nel026.jpg', 'NEL/Nel028.jpg', 'NEL/Nel033.jpg', 'NEL/Nel035.jpg', 'NEL/Nel037.jpg', 'NEL/Nel039.jpg', 'NEL/Nel041.jpg', 'NEL/Nel085.jpg', 'NEL/Nel087.jpg', 'NEL/Nel089.jpg', 'NEL/Nel091.jpg', 'NEL/Nel092.jpg', 'NEL/Nel095.jpg', 'NEL/Nel097.jpg', 'NEL/Nel098.jpg', 'NEL/Nel100.jpg', 'NFL/Nfl068.jpg', 'NGL/Ngl047.jpg', 'NHL/Nhl011.jpg', 'NML/Nml098.jpg']

split:
['train', 'validation', 'test']

clinic_path:
['/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL025.JPG', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL027.JPG', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel032.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL034.JPG', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL036.JPG', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel038.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel040.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel084.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel086.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL088.JPG', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL090.JPG', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL093.JPG', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel094.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL096.JPG', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL099.JPG', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel101.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NFL/Nfl067.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NGL/NGL046.JPG', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NHL/Nhl010.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NML/NML097.JPG']

derm_path:
['/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel026.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel028.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel033.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel035.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel037.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel039.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel041.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel085.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel087.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel089.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel091.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel092.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel095.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel097.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel098.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel100.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NFL/Nfl068.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NGL/Ngl047.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NHL/Nhl011.jpg', '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NML/Nml098.jpg']

In [3]:
# Verify the untouched Derm7pt test split and label distribution

derm7pt_test = derm7pt_metadata[
    derm7pt_metadata["split"] == "test"
].copy()

print("=" * 60)
print("DERM7PT TEST SPLIT")
print("=" * 60)

print("Number of test cases:", len(derm7pt_test))

print("\nBinary label distribution:")
print(derm7pt_test["binary_label"].value_counts())

print("\nNumeric label distribution:")
print(derm7pt_test["label"].value_counts().sort_index())

print("\nImage path availability:")

print(
    "Dermoscopic paths:",
    derm7pt_test["derm_path"].notna().sum(),
    "/",
    len(derm7pt_test)
)

print(
    "Clinical paths:",
    derm7pt_test["clinic_path"].notna().sum(),
    "/",
    len(derm7pt_test)
)

print("\nSplit distribution:")
print(derm7pt_test["split"].value_counts())

print("\n" + "=" * 60)
print("TEST SPLIT VERIFICATION COMPLETE")
print("=" * 60)

============================================================
DERM7PT TEST SPLIT
============================================================
Number of test cases: 395

Binary label distribution:
binary_label
Non-Melanoma    294
Melanoma        101
Name: count, dtype: int64

Numeric label distribution:
label
0    294
1    101
Name: count, dtype: int64

Image path availability:
Dermoscopic paths: 395 / 395
Clinical paths: 395 / 395

Split distribution:
split
test    395
Name: count, dtype: int64

============================================================
TEST SPLIT VERIFICATION COMPLETE
============================================================

In [4]:
# Create the Derm7pt dermoscopic dataset for external evaluation

import os
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

class Derm7ptExternalDataset(Dataset):
    def __init__(self, dataframe, image_root, transform=None):
        self.dataframe = dataframe.reset_index(drop=True)
        self.image_root = image_root
        self.transform = transform

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, index):
        row = self.dataframe.iloc[index]

        relative_path = row["derm"].replace("\\", "/")
        image_path = os.path.join(
            self.image_root,
            relative_path
        )

        image = Image.open(image_path).convert("RGB")
        label = int(row["label"])

        if self.transform is not None:
            image = self.transform(image)

        return image, label


# Use the same ImageNet normalization as HAM10000 evaluation
derm7pt_eval_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


derm7pt_test_dataset = Derm7ptExternalDataset(
    dataframe=derm7pt_test,
    image_root=DERM7PT_IMAGE_ROOT,
    transform=derm7pt_eval_transform
)


derm7pt_test_loader = DataLoader(
    derm7pt_test_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)


print("=" * 60)
print("DERM7PT EXTERNAL EVALUATION DATASET")
print("=" * 60)

print("Test cases:", len(derm7pt_test_dataset))
print("Batches:", len(derm7pt_test_loader))

print("\nExpected labels:")
print("Non-Melanoma:", (derm7pt_test["label"] == 0).sum())
print("Melanoma:", (derm7pt_test["label"] == 1).sum())

print("\n" + "=" * 60)
print("DATASET READY")
print("=" * 60)

============================================================
DERM7PT EXTERNAL EVALUATION DATASET
============================================================
Test cases: 395
Batches: 13

Expected labels:
Non-Melanoma: 294
Melanoma: 101

============================================================
DATASET READY
============================================================

In [5]:
# Sanity-check one Derm7pt dermoscopic evaluation sample

sample_image, sample_label = derm7pt_test_dataset[0]

print("=" * 60)
print("DERM7PT SAMPLE SANITY CHECK")
print("=" * 60)

print("Tensor shape:", sample_image.shape)
print("Tensor dtype:", sample_image.dtype)
print("Tensor minimum:", sample_image.min().item())
print("Tensor maximum:", sample_image.max().item())
print("Label:", sample_label)
print("Expected label:", int(derm7pt_test.iloc[0]["label"]))
print("Case number:", int(derm7pt_test.iloc[0]["case_num"]))
print("Dermoscopic file:", derm7pt_test.iloc[0]["derm"])

print("\n" + "=" * 60)
print("SANITY CHECK COMPLETE")
print("=" * 60)

============================================================
DERM7PT SAMPLE SANITY CHECK
============================================================
Tensor shape: torch.Size([3, 224, 224])
Tensor dtype: torch.float32
Tensor minimum: -2.1179039478302
Tensor maximum: 2.640000104904175
Label: 0
Expected label: 0
Case number: 4
Dermoscopic file: NEL/Nel035.jpg

============================================================
SANITY CHECK COMPLETE
============================================================

In [6]:
# Recreate the five trained HAM10000 model architectures

import torch
import torch.nn as nn
from torchvision import models

NUM_CLASSES = 2

print("=" * 60)
print("RECREATING HAM10000 MODEL ARCHITECTURES")
print("=" * 60)


# AlexNet
alexnet = models.alexnet(weights=None)
alexnet.classifier[6] = nn.Linear(
    alexnet.classifier[6].in_features,
    NUM_CLASSES
)


# VGG16
vgg16 = models.vgg16(weights=None)
vgg16.classifier[6] = nn.Linear(
    vgg16.classifier[6].in_features,
    NUM_CLASSES
)


# VGG19
vgg19 = models.vgg19(weights=None)
vgg19.classifier[6] = nn.Linear(
    vgg19.classifier[6].in_features,
    NUM_CLASSES
)


# ResNet50
resnet50 = models.resnet50(weights=None)
resnet50.fc = nn.Linear(
    resnet50.fc.in_features,
    NUM_CLASSES
)


# EfficientNet-B0
efficientnet_b0 = models.efficientnet_b0(weights=None)
efficientnet_b0.classifier[1] = nn.Linear(
    efficientnet_b0.classifier[1].in_features,
    NUM_CLASSES
)


model_dict = {
    "AlexNet": alexnet,
    "VGG16": vgg16,
    "VGG19": vgg19,
    "ResNet50": resnet50,
    "EfficientNet-B0": efficientnet_b0
}


for name, model in model_dict.items():
    total_params = sum(
        parameter.numel()
        for parameter in model.parameters()
    )
    print(f"{name}: {total_params:,} parameters")


print("\n" + "=" * 60)
print("MODEL ARCHITECTURES READY")
print("=" * 60)

============================================================
RECREATING HAM10000 MODEL ARCHITECTURES
============================================================
AlexNet: 57,012,034 parameters
VGG16: 134,268,738 parameters
VGG19: 139,578,434 parameters
ResNet50: 23,512,130 parameters
EfficientNet-B0: 4,010,110 parameters

============================================================
MODEL ARCHITECTURES READY
============================================================

In [7]:
# Locate the saved HAM10000 model checkpoints for external evaluation

import os

checkpoint_paths = {
    "AlexNet": "/kaggle/working/ham10000_alexnet_balanced_best.pth",
    "VGG16": "/kaggle/working/ham10000_vgg16_balanced_best.pth",
    "VGG19": "/kaggle/working/ham10000_vgg19_balanced_best.pth",
    "ResNet50": "/kaggle/working/ham10000_resnet50_balanced_best.pth",
    "EfficientNet-B0": "/kaggle/working/ham10000_efficientnet_b0_balanced_best.pth"
}

print("=" * 60)
print("HAM10000 CHECKPOINT VERIFICATION")
print("=" * 60)

for name, path in checkpoint_paths.items():
    exists = os.path.exists(path)

    if exists:
        size_mb = os.path.getsize(path) / (1024 ** 2)
        print(f"{name}: FOUND | {size_mb:.2f} MB")
    else:
        print(f"{name}: NOT FOUND")

print("\n" + "=" * 60)
print("CHECKPOINT VERIFICATION COMPLETE")
print("=" * 60)

============================================================
HAM10000 CHECKPOINT VERIFICATION
============================================================
AlexNet: NOT FOUND
VGG16: NOT FOUND
VGG19: NOT FOUND
ResNet50: NOT FOUND
EfficientNet-B0: NOT FOUND

============================================================
CHECKPOINT VERIFICATION COMPLETE
============================================================

In [8]:
# Search the current Kaggle working directory for existing model backups

import os

print("=" * 60)
print("SEARCHING FOR HAM10000 MODEL BACKUPS")
print("=" * 60)

for filename in sorted(os.listdir("/kaggle/working")):
    if "HAM10000" in filename or "ham10000" in filename:
        full_path = os.path.join("/kaggle/working", filename)
        size_mb = os.path.getsize(full_path) / (1024 ** 2)

        print(f"{filename} | {size_mb:.2f} MB")

print("\n" + "=" * 60)
print("BACKUP SEARCH COMPLETE")
print("=" * 60)

============================================================
SEARCHING FOR HAM10000 MODEL BACKUPS
============================================================

============================================================
BACKUP SEARCH COMPLETE
============================================================

In [9]:
# Locate the attached five trained model backup dataset

import os

print("=" * 60)
print("SEARCHING KAGGLE INPUT DATASETS")
print("=" * 60)

for root, dirs, files in os.walk("/kaggle/input"):
    for filename in files:
        if (
            "HAM10000" in filename
            or "ham10000" in filename
            or "AlexNet" in filename
            or "VGG16" in filename
            or "VGG19" in filename
            or "ResNet50" in filename
            or "EfficientNet" in filename
        ):
            full_path = os.path.join(root, filename)
            size_mb = os.path.getsize(full_path) / (1024 ** 2)

            print(f"{full_path} | {size_mb:.2f} MB")

print("\n" + "=" * 60)
print("SEARCH COMPLETE")
print("=" * 60)

============================================================
SEARCHING KAGGLE INPUT DATASETS
============================================================
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_ResNet50_Balanced_Baseline_Backup/ham10000_resnet50_balanced_training_history.pt | 0.00 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_ResNet50_Balanced_Baseline_Backup/ham10000_resnet50_balanced_best.pth | 269.53 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_ResNet50_Balanced_Baseline_Backup/ham10000_resnet50_balanced_results.json | 0.00 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_AlexNet_Balanced_Baseline_Backup/ham10000_alexnet_balanced_results.json | 0.00 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_AlexNet_Balanced_Baseline_Backup/ham10000_alexnet_balanced_training_history.pt | 0.00 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_AlexNet_Balanced_Baseline_Backup/ham10000_alexnet_balanced_best.pth | 652.47 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_VGG19_Balanced_Baseline_Backup/ham10000_vgg19_balanced_best.pth | 1597.40 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_VGG19_Balanced_Baseline_Backup/ham10000_vgg19_balanced_training_history.pt | 0.00 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_VGG19_Balanced_Baseline_Backup/ham10000_vgg19_balanced_results.json | 0.00 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_EfficientNetB0_Balanced_Baseline_Backup/ham10000_efficientnet_b0_balanced_results.json | 0.00 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_EfficientNetB0_Balanced_Baseline_Backup/ham10000_efficientnet_b0_balanced_training_history.pt | 0.00 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_EfficientNetB0_Balanced_Baseline_Backup/ham10000_efficientnet_b0_balanced_best.pth | 46.38 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_VGG16_Balanced_Baseline_Backup/ham10000_vgg16_balanced_results.json | 0.00 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_VGG16_Balanced_Baseline_Backup/ham10000_vgg16_balanced_training_history.pt | 0.01 MB
/kaggle/input/datasets/akansha1009/5-trained-models/HAM10000_VGG16_Balanced_Baseline_Backup/ham10000_vgg16_balanced_best.pth | 1536.63 MB

============================================================
SEARCH COMPLETE
============================================================

In [12]:
# Load the trained HAM10000 checkpoints from their saved training checkpoints

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_checkpoint_paths = {
    "AlexNet": "/kaggle/input/datasets/akansha1009/5-trained-models/"
               "HAM10000_AlexNet_Balanced_Baseline_Backup/"
               "ham10000_alexnet_balanced_best.pth",

    "VGG16": "/kaggle/input/datasets/akansha1009/5-trained-models/"
             "HAM10000_VGG16_Balanced_Baseline_Backup/"
             "ham10000_vgg16_balanced_best.pth",

    "VGG19": "/kaggle/input/datasets/akansha1009/5-trained-models/"
             "HAM10000_VGG19_Balanced_Baseline_Backup/"
             "ham10000_vgg19_balanced_best.pth",

    "ResNet50": "/kaggle/input/datasets/akansha1009/5-trained-models/"
                "HAM10000_ResNet50_Balanced_Baseline_Backup/"
                "ham10000_resnet50_balanced_best.pth",

    "EfficientNet-B0": "/kaggle/input/datasets/akansha1009/5-trained-models/"
                       "HAM10000_EfficientNetB0_Balanced_Baseline_Backup/"
                       "ham10000_efficientnet_b0_balanced_best.pth"
}


model_architectures = {
    "AlexNet": alexnet,
    "VGG16": vgg16,
    "VGG19": vgg19,
    "ResNet50": resnet50,
    "EfficientNet-B0": efficientnet_b0
}


loaded_models = {}

print("=" * 60)
print("LOADING FIVE TRAINED HAM10000 MODELS")
print("=" * 60)

for name, model in model_architectures.items():

    checkpoint = torch.load(
        model_checkpoint_paths[name],
        map_location="cpu",
        weights_only=False
    )

    state_dict = checkpoint["model_state_dict"]

    cleaned_state_dict = {}

    for key, value in state_dict.items():
        if key.startswith("module."):
            key = key.replace("module.", "", 1)

        cleaned_state_dict[key] = value

    model.load_state_dict(cleaned_state_dict)

    model = model.to(device)
    model.eval()

    loaded_models[name] = model

    print(
        f"{name}: LOADED | "
        f"Best epoch: {checkpoint.get('epoch', 'N/A')} | "
        f"Best Val F1: {checkpoint.get('best_val_f1', 'N/A')}"
    )


print("\nDevice:", device)
print("Models loaded:", len(loaded_models))

print("\n" + "=" * 60)
print("ALL FIVE TRAINED MODELS LOADED SUCCESSFULLY")
print("=" * 60)

============================================================
LOADING FIVE TRAINED HAM10000 MODELS
============================================================
AlexNet: LOADED | Best epoch: 8 | Best Val F1: 0.5481171548117155
VGG16: LOADED | Best epoch: 10 | Best Val F1: 0.6008771929824561
VGG19: LOADED | Best epoch: 2 | Best Val F1: 0.6440677966101694
ResNet50: LOADED | Best epoch: 7 | Best Val F1: 0.6255924170616114
EfficientNet-B0: LOADED | Best epoch: 9 | Best Val F1: 0.6219512195121951

Device: cuda
Models loaded: 5

============================================================
ALL FIVE TRAINED MODELS LOADED SUCCESSFULLY
============================================================

In [13]:
# Sanity-check one Derm7pt image with all five trained models

import torch

sample_images, sample_labels = next(iter(derm7pt_test_loader))

sample_image = sample_images[0:1].to(device)
sample_label = sample_labels[0].item()

print("=" * 60)
print("DERM7PT SINGLE-IMAGE INFERENCE SANITY CHECK")
print("=" * 60)

print("Input shape:", tuple(sample_image.shape))
print("True label:", sample_label)

for name, model in loaded_models.items():

    with torch.no_grad():
        output = model(sample_image)
        probability = torch.softmax(output, dim=1)[0, 1].item()
        prediction = int(probability >= 0.5)

    print(
        f"{name}: "
        f"Prediction {prediction} | "
        f"Melanoma probability {probability:.4f} | "
        f"Output shape {tuple(output.shape)}"
    )

print("\n" + "=" * 60)
print("SANITY CHECK COMPLETE")
print("=" * 60)

============================================================
DERM7PT SINGLE-IMAGE INFERENCE SANITY CHECK
============================================================
Input shape: (1, 3, 224, 224)
True label: 0
AlexNet: Prediction 1 | Melanoma probability 0.9051 | Output shape (1, 2)
VGG16: Prediction 1 | Melanoma probability 0.9796 | Output shape (1, 2)
VGG19: Prediction 0 | Melanoma probability 0.1675 | Output shape (1, 2)
ResNet50: Prediction 0 | Melanoma probability 0.0368 | Output shape (1, 2)
EfficientNet-B0: Prediction 1 | Melanoma probability 0.8338 | Output shape (1, 2)

============================================================
SANITY CHECK COMPLETE
============================================================

In [14]:
# Evaluate all five frozen HAM10000 models on the untouched Derm7pt test set

import torch
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

print("=" * 60)
print("DERM7PT EXTERNAL EVALUATION")
print("=" * 60)

external_results = {}

criterion = torch.nn.CrossEntropyLoss()

for name, model in loaded_models.items():

    print(f"\nEvaluating {name}...")

    model.eval()

    all_labels = []
    all_predictions = []
    all_probabilities = []
    total_loss = 0.0
    total_samples = 0

    with torch.no_grad():

        for images, labels in derm7pt_test_loader:

            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            outputs = model(images)

            loss = criterion(outputs, labels)

            probabilities = torch.softmax(outputs, dim=1)[:, 1]
            predictions = (probabilities >= 0.5).long()

            batch_size = labels.size(0)

            total_loss += loss.item() * batch_size
            total_samples += batch_size

            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predictions.cpu().numpy())
            all_probabilities.extend(probabilities.cpu().numpy())

    all_labels = np.array(all_labels)
    all_predictions = np.array(all_predictions)
    all_probabilities = np.array(all_probabilities)

    test_loss = total_loss / total_samples

    accuracy = accuracy_score(all_labels, all_predictions)
    precision = precision_score(
        all_labels,
        all_predictions,
        zero_division=0
    )
    recall = recall_score(
        all_labels,
        all_predictions,
        zero_division=0
    )
    f1 = f1_score(
        all_labels,
        all_predictions,
        zero_division=0
    )
    roc_auc = roc_auc_score(
        all_labels,
        all_probabilities
    )

    cm = confusion_matrix(
        all_labels,
        all_predictions
    )

    external_results[name] = {
        "test_loss": test_loss,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "roc_auc": roc_auc,
        "confusion_matrix": cm.tolist()
    }

    print(
        f"Loss: {test_loss:.4f} | "
        f"Accuracy: {accuracy:.4f} | "
        f"Precision: {precision:.4f} | "
        f"Recall: {recall:.4f} | "
        f"F1: {f1:.4f} | "
        f"ROC-AUC: {roc_auc:.4f}"
    )

    print("Confusion Matrix:")
    print(cm)

print("\n" + "=" * 60)
print("DERM7PT EXTERNAL EVALUATION COMPLETE")
print("=" * 60)

============================================================
DERM7PT EXTERNAL EVALUATION
============================================================

Evaluating AlexNet...
Loss: 0.8385 | Accuracy: 0.7747 | Precision: 0.6000 | Recall: 0.3564 | F1: 0.4472 | ROC-AUC: 0.6861
Confusion Matrix:
[[270  24]
 [ 65  36]]

Evaluating VGG16...
Loss: 0.9247 | Accuracy: 0.7544 | Precision: 0.5357 | Recall: 0.2970 | F1: 0.3822 | ROC-AUC: 0.7117
Confusion Matrix:
[[268  26]
 [ 71  30]]

Evaluating VGG19...
Loss: 0.5992 | Accuracy: 0.7747 | Precision: 0.7500 | Recall: 0.1782 | F1: 0.2880 | ROC-AUC: 0.6587
Confusion Matrix:
[[288   6]
 [ 83  18]]

Evaluating ResNet50...
Loss: 0.9090 | Accuracy: 0.7949 | Precision: 0.7632 | Recall: 0.2871 | F1: 0.4173 | ROC-AUC: 0.7687
Confusion Matrix:
[[285   9]
 [ 72  29]]

Evaluating EfficientNet-B0...
Loss: 0.9244 | Accuracy: 0.7696 | Precision: 0.6316 | Recall: 0.2376 | F1: 0.3453 | ROC-AUC: 0.7414
Confusion Matrix:
[[280  14]
 [ 77  24]]

============================================================
DERM7PT EXTERNAL EVALUATION COMPLETE
============================================================

In [15]:
# Save the Derm7pt external benchmark results for permanent project tracking

import json
import os

output_path = "/kaggle/working/derm7pt_external_benchmark_results.json"

benchmark_data = {
    "dataset": "Derm7pt",
    "split": "official_test",
    "modality": "dermoscopic",
    "task": "binary melanoma vs non-melanoma",
    "num_test_cases": 395,
    "threshold": 0.5,
    "models": external_results
}

with open(output_path, "w") as f:
    json.dump(benchmark_data, f, indent=4)

print("=" * 60)
print("DERM7PT BENCHMARK SAVED")
print("=" * 60)
print("File:", output_path)
print("Models saved:", len(external_results))
print("Test cases:", benchmark_data["num_test_cases"])

============================================================
DERM7PT BENCHMARK SAVED
============================================================
File: /kaggle/working/derm7pt_external_benchmark_results.json
Models saved: 5
Test cases: 395

In [16]:
# Create the combined HAM10000 and Derm7pt benchmark comparison

import pandas as pd

ham10000_results = {
    "AlexNet": {
        "accuracy": 0.845539,
        "precision": 0.385965,
        "recall": 0.658683,
        "f1": 0.486726,
        "roc_auc": 0.870407
    },
    "VGG16": {
        "accuracy": 0.856192,
        "precision": 0.415225,
        "recall": 0.718563,
        "f1": 0.526316,
        "roc_auc": 0.896064
    },
    "VGG19": {
        "accuracy": 0.903462,
        "precision": 0.568750,
        "recall": 0.544910,
        "f1": 0.556575,
        "roc_auc": 0.872484
    },
    "ResNet50": {
        "accuracy": 0.881491,
        "precision": 0.477178,
        "recall": 0.688623,
        "f1": 0.563725,
        "roc_auc": 0.908995
    },
    "EfficientNet-B0": {
        "accuracy": 0.895473,
        "precision": 0.534722,
        "recall": 0.461078,
        "f1": 0.495177,
        "roc_auc": 0.888434
    }
}

rows = []

for model_name in ham10000_results:

    ham = ham10000_results[model_name]
    derm = external_results[model_name]

    rows.append({
        "Model": model_name,

        "HAM10000 Accuracy": ham["accuracy"],
        "Derm7pt Accuracy": derm["accuracy"],
        "Accuracy Change": derm["accuracy"] - ham["accuracy"],

        "HAM10000 Precision": ham["precision"],
        "Derm7pt Precision": derm["precision"],
        "Precision Change": derm["precision"] - ham["precision"],

        "HAM10000 Recall": ham["recall"],
        "Derm7pt Recall": derm["recall"],
        "Recall Change": derm["recall"] - ham["recall"],

        "HAM10000 F1": ham["f1"],
        "Derm7pt F1": derm["f1"],
        "F1 Change": derm["f1"] - ham["f1"],

        "HAM10000 ROC-AUC": ham["roc_auc"],
        "Derm7pt ROC-AUC": derm["roc_auc"],
        "ROC-AUC Change": derm["roc_auc"] - ham["roc_auc"]
    })

combined_benchmark = pd.DataFrame(rows)

print("=" * 60)
print("HAM10000 vs DERM7PT GENERALIZATION COMPARISON")
print("=" * 60)

display(
    combined_benchmark.style.format({
        col: "{:.4f}"
        for col in combined_benchmark.columns
        if col != "Model"
    })
)

print("\n" + "=" * 60)
print("AVERAGE PERFORMANCE CHANGE")
print("=" * 60)

change_columns = [
    "Accuracy Change",
    "Precision Change",
    "Recall Change",
    "F1 Change",
    "ROC-AUC Change"
]

for column in change_columns:
    print(f"{column}: {combined_benchmark[column].mean():.4f}")

============================================================
HAM10000 vs DERM7PT GENERALIZATION COMPARISON
============================================================

============================================================
AVERAGE PERFORMANCE CHANGE
============================================================
Accuracy Change: -0.1028
Precision Change: 0.1797
Recall Change: -0.3431
F1 Change: -0.1497
ROC-AUC Change: -0.1740

In [17]:
# Save the combined HAM10000 and Derm7pt benchmark for project tracking

import json

output_path = "/kaggle/working/combined_ham10000_derm7pt_benchmark.json"

combined_data = {
    "description": "Five-model in-domain and cross-dataset benchmark",
    "ham10000": ham10000_results,
    "derm7pt": external_results,
    "average_change": {
        column: float(combined_benchmark[column].mean())
        for column in [
            "Accuracy Change",
            "Precision Change",
            "Recall Change",
            "F1 Change",
            "ROC-AUC Change"
        ]
    }
}

with open(output_path, "w") as f:
    json.dump(combined_data, f, indent=4)

print("=" * 60)
print("COMBINED BENCHMARK SAVED")
print("=" * 60)
print("File:", output_path)
print("Datasets:", "HAM10000 + Derm7pt")
print("Models:", len(ham10000_results))
print("Status: SAVED SUCCESSFULLY")

============================================================
COMBINED BENCHMARK SAVED
============================================================
File: /kaggle/working/combined_ham10000_derm7pt_benchmark.json
Datasets: HAM10000 + Derm7pt
Models: 5
Status: SAVED SUCCESSFULLY

In [12]:
# Verify the frozen Derm7pt dataset before retraining 

import os
import pandas as pd

DATASET_ROOT = "/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset"
IMAGE_ROOT = os.path.join(DATASET_ROOT, "Derm7pt_Kaggle_Ready", "images")
METADATA_PATH = os.path.join(DATASET_ROOT, "Derm7pt_split_metadata.csv")

print("Dataset root exists:", os.path.exists(DATASET_ROOT))
print("Image folder exists:", os.path.exists(IMAGE_ROOT))
print("Frozen metadata exists:", os.path.exists(METADATA_PATH))

if os.path.exists(METADATA_PATH):
    metadata = pd.read_csv(METADATA_PATH)
    print("\nMetadata shape:", metadata.shape)
    print("Columns:", list(metadata.columns))
    print("\nSplit counts:")
    print(metadata["split"].value_counts())

print("\nNumber of images:", len(os.listdir(IMAGE_ROOT)) if os.path.exists(IMAGE_ROOT) else 0)

Dataset root exists: True
Image folder exists: True
Frozen metadata exists: True

Metadata shape: (1011, 9)
Columns: ['case_num', 'diagnosis', 'binary_label', 'label', 'clinic', 'derm', 'split', 'clinic_path', 'derm_path']

Split counts:
split
train         413
test          395
validation    203
Name: count, dtype: int64

Number of images: 35

In [13]:
# --- Restore the Derm7pt PyTorch dataset class ---

import os
import pandas as pd
from PIL import Image
from torch.utils.data import Dataset

class Derm7ptDataset(Dataset):

    def __init__(self, dataframe, transform=None):
        self.dataframe = dataframe.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        row = self.dataframe.iloc[idx]

        image_path = row["derm_path"]
        image = Image.open(image_path).convert("RGB")

        label = int(row["binary_label"])

        if self.transform:
            image = self.transform(image)

        return image, label

train_df = metadata[metadata["split"] == "train"].copy()
val_df = metadata[metadata["split"] == "validation"].copy()
test_df = metadata[metadata["split"] == "test"].copy()

print("Train cases:", len(train_df))
print("Validation cases:", len(val_df))
print("Test cases:", len(test_df))

print("\nDataset class restored successfully.")

Train cases: 413
Validation cases: 203
Test cases: 395

Dataset class restored successfully.

In [14]:
# --- Restore the original Derm7pt image transformations ---

import torch
from torchvision import transforms

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.2),
    transforms.RandomRotation(15),
    transforms.ColorJitter(
        brightness=0.15,
        contrast=0.15,
        saturation=0.10,
        hue=0.02
    ),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD)
])

eval_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD)
])

print("Training transform restored.")
print("Validation/test transform restored.")
print("Input size: 224 x 224")
print("ImageNet normalization restored.")

Training transform restored.
Validation/test transform restored.
Input size: 224 x 224
ImageNet normalization restored.

In [1]:
# DERM7PT KAGGLE INPUT VERIFICATION
# Purpose: Identify the exact mounted dataset path and verify the available files.

import os

print("DERM7PT KAGGLE INPUT VERIFICATION")

print("\nKaggle input directories:\n")

for dirname, _, filenames in os.walk("/kaggle/input"):
    level = dirname.replace("/kaggle/input", "").count(os.sep)
    
    if level <= 2:
        print(f"{dirname}/")
        
        for filename in filenames[:10]:
            print(f"  └── {filename}")

print("TOP-LEVEL KAGGLE INPUTS")

for item in os.listdir("/kaggle/input"):
    print("•", item)

print("✅ INPUT INSPECTION COMPLETED")

DERM7PT KAGGLE INPUT VERIFICATION

Kaggle input directories:

/kaggle/input/
/kaggle/input/datasets/
/kaggle/input/datasets/akansha1009/
TOP-LEVEL KAGGLE INPUTS
• datasets
✅ INPUT INSPECTION COMPLETED

In [18]:
# --- Convert frozen Derm7pt image paths from Colab paths to Kaggle paths ---

import os

def resolve_kaggle_image_path(path):
    filename = os.path.basename(path)

    for root, dirs, files in os.walk(IMAGE_ROOT):
        if filename in files:
            return os.path.join(root, filename)

    return None

train_df["derm_path"] = train_df["derm_path"].apply(resolve_kaggle_image_path)
val_df["derm_path"] = val_df["derm_path"].apply(resolve_kaggle_image_path)
test_df["derm_path"] = test_df["derm_path"].apply(resolve_kaggle_image_path)

missing_train = train_df["derm_path"].isna().sum()
missing_val = val_df["derm_path"].isna().sum()
missing_test = test_df["derm_path"].isna().sum()

print("Missing train dermoscopic images:", missing_train)
print("Missing validation dermoscopic images:", missing_val)
print("Missing test dermoscopic images:", missing_test)

print("\nPath example:")
print(train_df["derm_path"].iloc[0])

Missing train dermoscopic images: 0
Missing validation dermoscopic images: 0
Missing test dermoscopic images: 0

Path example:
/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_Kaggle_Ready/images/NEL/Nel026.jpg

In [20]:
# --- Convert Derm7pt binary labels to numeric class IDs ---

label_mapping = {
    "Non-Melanoma": 0,
    "Melanoma": 1
}

train_df["binary_label"] = train_df["binary_label"].map(label_mapping)
val_df["binary_label"] = val_df["binary_label"].map(label_mapping)
test_df["binary_label"] = test_df["binary_label"].map(label_mapping)

print("Train labels:")
print(train_df["binary_label"].value_counts().sort_index())

print("\nValidation labels:")
print(val_df["binary_label"].value_counts().sort_index())

print("\nTest labels:")
print(test_df["binary_label"].value_counts().sort_index())

print("\nMissing labels:")
print("Train:", train_df["binary_label"].isna().sum())
print("Validation:", val_df["binary_label"].isna().sum())
print("Test:", test_df["binary_label"].isna().sum())

Train labels:
binary_label
0    323
1     90
Name: count, dtype: int64

Validation labels:
binary_label
0    142
1     61
Name: count, dtype: int64

Test labels:
binary_label
0    294
1    101
Name: count, dtype: int64

Missing labels:
Train: 0
Validation: 0
Test: 0

In [21]:
# --- Recreate and verify the transformed Derm7pt datasets ---

train_dataset = Derm7ptDataset(
    train_df,
    transform=train_transform
)

val_dataset = Derm7ptDataset(
    val_df,
    transform=eval_transform
)

test_dataset = Derm7ptDataset(
    test_df,
    transform=eval_transform
)

print("Train dataset:", len(train_dataset))
print("Validation dataset:", len(val_dataset))
print("Test dataset:", len(test_dataset))

sample_image, sample_label = train_dataset[0]

print("\nSample image shape:", sample_image.shape)
print("Sample image dtype:", sample_image.dtype)
print("Sample label:", sample_label)
print("Sample image value range:",
      float(sample_image.min()),
      "to",
      float(sample_image.max()))

Train dataset: 413
Validation dataset: 203
Test dataset: 395

Sample image shape: torch.Size([3, 224, 224])
Sample image dtype: torch.float32
Sample label: 0
Sample image value range: -1.9124069213867188 to 1.906413197517395

In [22]:
# --- Create DataLoaders for EfficientNet-B0 training ---

from torch.utils.data import DataLoader

BATCH_SIZE = 32

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print("Train batches:", len(train_loader))
print("Validation batches:", len(val_loader))
print("Test batches:", len(test_loader))

images, labels = next(iter(train_loader))

print("\nBatch image shape:", images.shape)
print("Batch label shape:", labels.shape)
print("Batch image dtype:", images.dtype)
print("Batch label dtype:", labels.dtype)

Train batches: 13
Validation batches: 7
Test batches: 13

Batch image shape: torch.Size([32, 3, 224, 224])
Batch label shape: torch.Size([32])
Batch image dtype: torch.float32
Batch label dtype: torch.int64

In [23]:
# --- Restore EfficientNet-B0 class weights and training configuration ---

import torch
import torch.nn as nn
import torch.optim as optim

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

NUM_CLASSES = 2
NUM_EPOCHS = 20
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-5

class_counts = train_df["binary_label"].value_counts().sort_index()

class_weights = len(train_df) / (
    len(class_counts) * class_counts
)

class_weights = torch.tensor(
    class_weights.values,
    dtype=torch.float32,
    device=DEVICE
)

criterion = nn.CrossEntropyLoss(
    weight=class_weights
)

print("Device:", DEVICE)
print("Number of epochs:", NUM_EPOCHS)
print("Learning rate:", LEARNING_RATE)
print("Weight decay:", WEIGHT_DECAY)
print("Class weights:", class_weights)
print("AMP enabled:", torch.cuda.is_available())

Device: cuda
Number of epochs: 20
Learning rate: 0.0001
Weight decay: 1e-05
Class weights: tensor([0.6393, 2.2944], device='cuda:0')
AMP enabled: True

In [24]:
# --- Restore the EfficientNet-B0 binary classification model ---

import torch
import torch.nn as nn
from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights

model = efficientnet_b0(
    weights=EfficientNet_B0_Weights.DEFAULT
)

model.classifier[1] = nn.Linear(
    model.classifier[1].in_features,
    NUM_CLASSES
)

model = model.to(DEVICE)

print("Model:", "EfficientNet-B0")
print("Parameters:", sum(p.numel() for p in model.parameters()))
print("Device:", DEVICE)

Downloading: "https://download.pytorch.org/models/efficientnet_b0_rwightman-7f5810bc.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_b0_rwightman-7f5810bc.pth

100%|██████████| 20.5M/20.5M [00:00<00:00, 139MB/s]

Model: EfficientNet-B0
Parameters: 4010110
Device: cuda

In [25]:
# --- Test EfficientNet-B0 optimizer, AMP, forward pass, and one training batch ---

from torch.amp import autocast, GradScaler

optimizer = optim.Adam(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY
)

scaler = GradScaler("cuda", enabled=torch.cuda.is_available())

model.train()

images, labels = next(iter(train_loader))

images = images.to(DEVICE, non_blocking=True)
labels = labels.to(DEVICE, non_blocking=True)

optimizer.zero_grad(set_to_none=True)

with autocast("cuda", enabled=torch.cuda.is_available()):
    outputs = model(images)
    loss = criterion(outputs, labels)

scaler.scale(loss).backward()
scaler.step(optimizer)
scaler.update()

print("Single-batch test passed.")
print("Input shape:", images.shape)
print("Output shape:", outputs.shape)
print("Loss:", float(loss))
print("Optimizer:", type(optimizer).__name__)
print("AMP:", torch.cuda.is_available())

Single-batch test passed.
Input shape: torch.Size([32, 3, 224, 224])
Output shape: torch.Size([32, 2])
Loss: 0.7057165503501892
Optimizer: Adam
AMP: True

/tmp/ipykernel_58/3051173478.py:33: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:836.)
  print("Loss:", float(loss))

In [26]:
# --- Verify the EfficientNet-B0 single-batch training test ---

print("Single-batch test completed.")
print("Input shape:", images.shape)
print("Output shape:", outputs.shape)
print("Loss:", loss.detach().item())
print("Optimizer:", type(optimizer).__name__)
print("AMP:", torch.cuda.is_available())

Single-batch test completed.
Input shape: torch.Size([32, 3, 224, 224])
Output shape: torch.Size([32, 2])
Loss: 0.7057165503501892
Optimizer: Adam
AMP: True

In [27]:
# --- Train EfficientNet-B0 from a clean initialization for 20 epochs ---

import time
import copy
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

model = efficientnet_b0(
    weights=EfficientNet_B0_Weights.DEFAULT
)

model.classifier[1] = nn.Linear(
    model.classifier[1].in_features,
    NUM_CLASSES
)

model = model.to(DEVICE)

optimizer = optim.Adam(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY
)

scaler = GradScaler("cuda", enabled=torch.cuda.is_available())

best_val_f1 = -1.0
best_epoch = 0
best_model_state = None

history = {
    "train_loss": [],
    "val_loss": [],
    "val_accuracy": [],
    "val_precision": [],
    "val_recall": [],
    "val_f1": [],
    "val_roc_auc": []
}

start_time = time.time()

for epoch in range(1, NUM_EPOCHS + 1):

    model.train()

    running_loss = 0.0
    train_samples = 0

    for images, labels in train_loader:

        images = images.to(DEVICE, non_blocking=True)
        labels = labels.to(DEVICE, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with autocast("cuda", enabled=torch.cuda.is_available()):
            outputs = model(images)
            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        batch_size = labels.size(0)
        running_loss += loss.detach().item() * batch_size
        train_samples += batch_size

    train_loss = running_loss / train_samples

    model.eval()

    val_loss_total = 0.0
    val_samples = 0
    val_labels = []
    val_predictions = []
    val_probabilities = []

    with torch.no_grad():

        for images, labels in val_loader:

            images = images.to(DEVICE, non_blocking=True)
            labels = labels.to(DEVICE, non_blocking=True)

            with autocast("cuda", enabled=torch.cuda.is_available()):
                outputs = model(images)
                loss = criterion(outputs, labels)

            probabilities = torch.softmax(outputs, dim=1)[:, 1]
            predictions = torch.argmax(outputs, dim=1)

            batch_size = labels.size(0)

            val_loss_total += loss.detach().item() * batch_size
            val_samples += batch_size

            val_labels.extend(labels.cpu().numpy())
            val_predictions.extend(predictions.cpu().numpy())
            val_probabilities.extend(probabilities.cpu().numpy())

    val_loss = val_loss_total / val_samples

    val_accuracy = accuracy_score(val_labels, val_predictions)
    val_precision = precision_score(
        val_labels,
        val_predictions,
        zero_division=0
    )
    val_recall = recall_score(
        val_labels,
        val_predictions,
        zero_division=0
    )
    val_f1 = f1_score(
        val_labels,
        val_predictions,
        zero_division=0
    )
    val_roc_auc = roc_auc_score(
        val_labels,
        val_probabilities
    )

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["val_accuracy"].append(val_accuracy)
    history["val_precision"].append(val_precision)
    history["val_recall"].append(val_recall)
    history["val_f1"].append(val_f1)
    history["val_roc_auc"].append(val_roc_auc)

    if val_f1 > best_val_f1:

        best_val_f1 = val_f1
        best_epoch = epoch
        best_model_state = copy.deepcopy(model.state_dict())

    elapsed = (time.time() - start_time) / 60

    print(
        f"Epoch {epoch:02d}/{NUM_EPOCHS} | "
        f"Train Loss {train_loss:.4f} | "
        f"Val Loss {val_loss:.4f} | "
        f"Val Acc {val_accuracy:.4f} | "
        f"Val F1 {val_f1:.4f} | "
        f"Val AUC {val_roc_auc:.4f} | "
        f"Time {elapsed:.2f} min"
    )

print("\nTraining completed.")
print("Best validation F1:", best_val_f1)
print("Best epoch:", best_epoch)

Epoch 01/20 | Train Loss 0.6736 | Val Loss 0.6379 | Val Acc 0.6059 | Val F1 0.4030 | Val AUC 0.6448 | Time 0.31 min
Epoch 02/20 | Train Loss 0.6049 | Val Loss 0.5886 | Val Acc 0.7192 | Val F1 0.5440 | Val AUC 0.7229 | Time 0.39 min
Epoch 03/20 | Train Loss 0.5130 | Val Loss 0.5710 | Val Acc 0.7044 | Val F1 0.5312 | Val AUC 0.7542 | Time 0.46 min
Epoch 04/20 | Train Loss 0.4579 | Val Loss 0.5353 | Val Acc 0.7241 | Val F1 0.5333 | Val AUC 0.7776 | Time 0.53 min
Epoch 05/20 | Train Loss 0.4087 | Val Loss 0.5249 | Val Acc 0.7389 | Val F1 0.5546 | Val AUC 0.7809 | Time 0.61 min
Epoch 06/20 | Train Loss 0.3482 | Val Loss 0.5003 | Val Acc 0.7685 | Val F1 0.6050 | Val AUC 0.8050 | Time 0.69 min
Epoch 07/20 | Train Loss 0.2967 | Val Loss 0.4897 | Val Acc 0.7734 | Val F1 0.6230 | Val AUC 0.8144 | Time 0.77 min
Epoch 08/20 | Train Loss 0.2370 | Val Loss 0.4603 | Val Acc 0.8030 | Val F1 0.6226 | Val AUC 0.8286 | Time 0.84 min
Epoch 09/20 | Train Loss 0.1857 | Val Loss 0.4640 | Val Acc 0.7980 | Val F1 0.6372 | Val AUC 0.8305 | Time 0.92 min
Epoch 10/20 | Train Loss 0.1699 | Val Loss 0.4898 | Val Acc 0.7783 | Val F1 0.6218 | Val AUC 0.8245 | Time 0.99 min
Epoch 11/20 | Train Loss 0.1340 | Val Loss 0.5120 | Val Acc 0.7833 | Val F1 0.5926 | Val AUC 0.8142 | Time 1.07 min
Epoch 12/20 | Train Loss 0.1169 | Val Loss 0.4989 | Val Acc 0.8128 | Val F1 0.6481 | Val AUC 0.8157 | Time 1.14 min
Epoch 13/20 | Train Loss 0.1092 | Val Loss 0.5168 | Val Acc 0.7980 | Val F1 0.6095 | Val AUC 0.8107 | Time 1.21 min
Epoch 14/20 | Train Loss 0.1020 | Val Loss 0.5633 | Val Acc 0.7833 | Val F1 0.5600 | Val AUC 0.8054 | Time 1.29 min
Epoch 15/20 | Train Loss 0.0732 | Val Loss 0.5589 | Val Acc 0.7882 | Val F1 0.5905 | Val AUC 0.8150 | Time 1.37 min
Epoch 16/20 | Train Loss 0.0759 | Val Loss 0.5723 | Val Acc 0.7980 | Val F1 0.6095 | Val AUC 0.8112 | Time 1.44 min
Epoch 17/20 | Train Loss 0.0544 | Val Loss 0.6097 | Val Acc 0.8030 | Val F1 0.6429 | Val AUC 0.8021 | Time 1.51 min
Epoch 18/20 | Train Loss 0.0624 | Val Loss 0.6198 | Val Acc 0.8030 | Val F1 0.6078 | Val AUC 0.7974 | Time 1.59 min
Epoch 19/20 | Train Loss 0.0492 | Val Loss 0.6699 | Val Acc 0.8177 | Val F1 0.6263 | Val AUC 0.7799 | Time 1.67 min
Epoch 20/20 | Train Loss 0.0600 | Val Loss 0.5941 | Val Acc 0.8030 | Val F1 0.6296 | Val AUC 0.8224 | Time 1.74 min

Training completed.
Best validation F1: 0.6481481481481481
Best epoch: 12

In [28]:
# --- Save the best EfficientNet-B0 checkpoint selected by validation F1 ---

EFFICIENTNET_BEST_PATH = "/kaggle/working/derm7pt_efficientnet_b0_best.pth"

torch.save(
    {
        "model_state_dict": best_model_state,
        "best_epoch": best_epoch,
        "best_val_f1": best_val_f1,
        "model_name": "EfficientNet-B0",
        "num_classes": NUM_CLASSES
    },
    EFFICIENTNET_BEST_PATH
)

print("Best checkpoint saved.")
print("Path:", EFFICIENTNET_BEST_PATH)
print("Best epoch:", best_epoch)
print("Best validation F1:", best_val_f1)
print("File size:",
      round(os.path.getsize(EFFICIENTNET_BEST_PATH) / (1024 ** 2), 2),
      "MB")

Best checkpoint saved.
Path: /kaggle/working/derm7pt_efficientnet_b0_best.pth
Best epoch: 12
Best validation F1: 0.6481481481481481
File size: 15.59 MB

In [29]:
# --- Evaluate the best EfficientNet-B0 checkpoint on the untouched test set ---

checkpoint = torch.load(
    EFFICIENTNET_BEST_PATH,
    map_location=DEVICE
)

model.load_state_dict(checkpoint["model_state_dict"])
model.eval()

test_loss_total = 0.0
test_samples = 0

test_labels = []
test_predictions = []
test_probabilities = []

test_start_time = time.time()

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(DEVICE, non_blocking=True)
        labels = labels.to(DEVICE, non_blocking=True)

        with autocast("cuda", enabled=torch.cuda.is_available()):
            outputs = model(images)
            loss = criterion(outputs, labels)

        probabilities = torch.softmax(outputs, dim=1)[:, 1]
        predictions = torch.argmax(outputs, dim=1)

        batch_size = labels.size(0)

        test_loss_total += loss.detach().item() * batch_size
        test_samples += batch_size

        test_labels.extend(labels.cpu().numpy())
        test_predictions.extend(predictions.cpu().numpy())
        test_probabilities.extend(probabilities.cpu().numpy())

test_loss = test_loss_total / test_samples

test_accuracy = accuracy_score(
    test_labels,
    test_predictions
)

test_precision = precision_score(
    test_labels,
    test_predictions,
    zero_division=0
)

test_recall = recall_score(
    test_labels,
    test_predictions,
    zero_division=0
)

test_f1 = f1_score(
    test_labels,
    test_predictions,
    zero_division=0
)

test_roc_auc = roc_auc_score(
    test_labels,
    test_probabilities
)

from sklearn.metrics import confusion_matrix

test_confusion_matrix = confusion_matrix(
    test_labels,
    test_predictions
)

test_elapsed = time.time() - test_start_time

print("EfficientNet-B0 test evaluation completed.")
print("\nTest Loss:", round(test_loss, 6))
print("Accuracy:", round(test_accuracy, 6))
print("Precision:", round(test_precision, 6))
print("Recall:", round(test_recall, 6))
print("F1 Score:", round(test_f1, 6))
print("ROC-AUC:", round(test_roc_auc, 6))

print("\nConfusion Matrix:")
print(test_confusion_matrix)

print("\nEvaluation time:",
      round(test_elapsed / 60, 2),
      "minutes")

print("Average time per image:",
      round(test_elapsed / len(test_dataset), 4),
      "seconds")

EfficientNet-B0 test evaluation completed.

Test Loss: 0.499175
Accuracy: 0.805063
Precision: 0.646341
Recall: 0.524752
F1 Score: 0.579235
ROC-AUC: 0.826682

Confusion Matrix:
[[265  29]
 [ 48  53]]

Evaluation time: 0.06 minutes
Average time per image: 0.0087 seconds

In [30]:
# --- Save EfficientNet-B0 training history and final test results ---

import json
import torch

EFFICIENTNET_HISTORY_PATH = "/kaggle/working/derm7pt_efficientnet_b0_training_history.pt"
EFFICIENTNET_RESULTS_PATH = "/kaggle/working/derm7pt_efficientnet_b0_baseline_results.json"
EFFICIENTNET_FINAL_RESULTS_PATH = "/kaggle/working/derm7pt_efficientnet_b0_final_results.json"

torch.save(history, EFFICIENTNET_HISTORY_PATH)

baseline_results = {
    "model": "EfficientNet-B0",
    "dataset": "Derm7pt",
    "num_parameters": sum(p.numel() for p in model.parameters()),
    "epochs": NUM_EPOCHS,
    "learning_rate": LEARNING_RATE,
    "weight_decay": WEIGHT_DECAY,
    "best_epoch": best_epoch,
    "best_validation_f1": best_val_f1,
    "class_weights": class_weights.detach().cpu().tolist()
}

final_results = {
    **baseline_results,
    "test_loss": test_loss,
    "test_accuracy": test_accuracy,
    "test_precision": test_precision,
    "test_recall": test_recall,
    "test_f1": test_f1,
    "test_roc_auc": test_roc_auc,
    "confusion_matrix": test_confusion_matrix.tolist(),
    "evaluation_time_minutes": test_elapsed / 60,
    "average_time_per_image_seconds": test_elapsed / len(test_dataset)
}

with open(EFFICIENTNET_RESULTS_PATH, "w") as f:
    json.dump(baseline_results, f, indent=4)

with open(EFFICIENTNET_FINAL_RESULTS_PATH, "w") as f:
    json.dump(final_results, f, indent=4)

print("Training history saved:", EFFICIENTNET_HISTORY_PATH)
print("Baseline results saved:", EFFICIENTNET_RESULTS_PATH)
print("Final test results saved:", EFFICIENTNET_FINAL_RESULTS_PATH)

Training history saved: /kaggle/working/derm7pt_efficientnet_b0_training_history.pt
Baseline results saved: /kaggle/working/derm7pt_efficientnet_b0_baseline_results.json
Final test results saved: /kaggle/working/derm7pt_efficientnet_b0_final_results.json

In [31]:
# --- Verify all EfficientNet-B0 artifacts before creating the backup ---

import os

EFFICIENTNET_ARTIFACT_PATHS = [
    EFFICIENTNET_BEST_PATH,
    EFFICIENTNET_HISTORY_PATH,
    EFFICIENTNET_RESULTS_PATH,
    EFFICIENTNET_FINAL_RESULTS_PATH
]

print("EfficientNet-B0 artifact verification:\n")

all_present = True

for path in EFFICIENTNET_ARTIFACT_PATHS:
    exists = os.path.exists(path)
    size_mb = os.path.getsize(path) / (1024 ** 2) if exists else 0

    print(
        os.path.basename(path),
        "->",
        exists,
        "| Size:",
        round(size_mb, 2),
        "MB"
    )

    if not exists:
        all_present = False

print("\nAll artifacts present:", all_present)

EfficientNet-B0 artifact verification:

derm7pt_efficientnet_b0_best.pth -> True | Size: 15.59 MB
derm7pt_efficientnet_b0_training_history.pt -> True | Size: 0.0 MB
derm7pt_efficientnet_b0_baseline_results.json -> True | Size: 0.0 MB
derm7pt_efficientnet_b0_final_results.json -> True | Size: 0.0 MB

All artifacts present: True

In [32]:
# --- Create the permanent EfficientNet-B0 baseline backup ZIP ---

import zipfile
import os

EFFICIENTNET_BACKUP_PATH = "/kaggle/working/Derm7pt_EfficientNetB0_Baseline_Backup.zip"

with zipfile.ZipFile(
    EFFICIENTNET_BACKUP_PATH,
    "w",
    compression=zipfile.ZIP_DEFLATED
) as zipf:

    for path in EFFICIENTNET_ARTIFACT_PATHS:
        zipf.write(
            path,
            arcname=os.path.basename(path)
        )

print("Backup ZIP created.")
print("Path:", EFFICIENTNET_BACKUP_PATH)
print(
    "ZIP size:",
    round(os.path.getsize(EFFICIENTNET_BACKUP_PATH) / (1024 ** 2), 2),
    "MB"
)

print("\nBackup contents:")

with zipfile.ZipFile(EFFICIENTNET_BACKUP_PATH, "r") as zipf:
    for name in zipf.namelist():
        print(name)

Backup ZIP created.
Path: /kaggle/working/Derm7pt_EfficientNetB0_Baseline_Backup.zip
ZIP size: 14.39 MB

Backup contents:
derm7pt_efficientnet_b0_best.pth
derm7pt_efficientnet_b0_training_history.pt
derm7pt_efficientnet_b0_baseline_results.json
derm7pt_efficientnet_b0_final_results.json

In [2]:
# DERM7PT NEW SESSION RESTORATION
# Purpose: Reconnect the new Kaggle runtime to the frozen
#          Derm7pt dataset and restore the core metadata paths.

import os
import pandas as pd
import torch


BASE_PATH = (
    "/kaggle/input/datasets/akansha1009/"
    "derm7pt-frozen-dataset"
)

METADATA_PATH = (
    BASE_PATH +
    "/Derm7pt_split_metadata.csv"
)

IMAGE_ROOT = (
    BASE_PATH +
    "/Derm7pt_Kaggle_Ready/images"
)


print("DERM7PT NEW SESSION RESTORATION")

print("\nBase path:")
print(BASE_PATH)

print("\nBase path exists:")
print(os.path.exists(BASE_PATH))

print("\nMetadata path:")
print(METADATA_PATH)

print("\nMetadata exists:")
print(os.path.exists(METADATA_PATH))

print("\nImage root:")
print(IMAGE_ROOT)

print("\nImage root exists:")
print(os.path.exists(IMAGE_ROOT))


df = pd.read_csv(
    METADATA_PATH
)


print("\nFrozen metadata records:")
print(len(df))

print("\nColumns:")
print(df.columns.tolist())

print("\nSplit distribution:")
print(df["split"].value_counts())

print("\nBinary label distribution:")
print(df["binary_label"].value_counts())

print("\nPyTorch version:")
print(torch.__version__)

print("\nCUDA available:")
print(torch.cuda.is_available())

print("\nGPU count:")
print(torch.cuda.device_count())

print("✅ DERM7PT SESSION RESTORATION CHECK PASSED")

DERM7PT NEW SESSION RESTORATION

Base path:
/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset

Base path exists:
True

Metadata path:
/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_split_metadata.csv

Metadata exists:
True

Image root:
/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_Kaggle_Ready/images

Image root exists:
True

Frozen metadata records:
1011

Columns:
['case_num', 'diagnosis', 'binary_label', 'label', 'clinic', 'derm', 'split', 'clinic_path', 'derm_path']

Split distribution:
split
train         413
test          395
validation    203
Name: count, dtype: int64

Binary label distribution:
binary_label
Non-Melanoma    759
Melanoma        252
Name: count, dtype: int64

PyTorch version:
2.10.0+cu128

CUDA available:
True

GPU count:
2
✅ DERM7PT SESSION RESTORATION CHECK PASSED

In [9]:
# DERM7PT PYTORCH DATASET RESTORATION
# Purpose: Rebuild the train, validation, and test PyTorch
#          datasets from the frozen Derm7pt metadata.

from PIL import Image
from torch.utils.data import Dataset


class Derm7ptDataset(Dataset):

    def __init__(
        self,
        dataframe,
        image_root,
        transform=None
    ):

        self.dataframe = (
            dataframe.reset_index(
                drop=True
            )
        )

        self.image_root = image_root
        self.transform = transform


    def __len__(self):

        return len(
            self.dataframe
        )


    def __getitem__(
        self,
        index
    ):

        row = self.dataframe.iloc[index]

        image_path = row["derm_path"]

        relative_path = (
            image_path
            .replace(
                "/content/drive/MyDrive/"
                "Melanoma Skin Lesion Analysis Project/"
                "data/Derm7pt/raw/release_v0/",
                ""
            )
        )

        full_path = (
            self.image_root
            .replace(
                "/images",
                ""
            )
            + "/"
            + relative_path
        )


        image = Image.open(
            full_path
        ).convert("RGB")


        label = (
            1
            if row["binary_label"] == "Melanoma"
            else 0
        )


        if self.transform is not None:

            image = self.transform(
                image
            )


        return (
            image,
            label
        )


train_df = df[
    df["split"] == "train"
].copy()

val_df = df[
    df["split"] == "validation"
].copy()

test_df = df[
    df["split"] == "test"
].copy()


train_dataset = Derm7ptDataset(
    train_df,
    IMAGE_ROOT
)

val_dataset = Derm7ptDataset(
    val_df,
    IMAGE_ROOT
)

test_dataset = Derm7ptDataset(
    test_df,
    IMAGE_ROOT
)


sample_image, sample_label = (
    train_dataset[0]
)


print("DERM7PT PYTORCH DATASET RESTORATION")

print("\nTraining samples:")
print(len(train_dataset))

print("\nValidation samples:")
print(len(val_dataset))

print("\nTest samples:")
print(len(test_dataset))

print("\nSample image type:")
print(type(sample_image))

print("\nSample image size:")
print(sample_image.size)

print("\nSample label:")
print(sample_label)

print("✅ DERM7PT PYTORCH DATASETS RESTORED")

DERM7PT PYTORCH DATASET RESTORATION

Training samples:
413

Validation samples:
203

Test samples:
395

Sample image type:
<class 'PIL.Image.Image'>

Sample image size:
(768, 512)

Sample label:
0
✅ DERM7PT PYTORCH DATASETS RESTORED

In [10]:
# 
# DERM7PT IMAGE TRANSFORMS RESTORATION
# Purpose: Restore the identical preprocessing used for the
#          Derm7pt ResNet-18 baseline and future models.

import torchvision.transforms as transforms


IMAGE_SIZE = 224


train_transform = transforms.Compose([
    transforms.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),
    transforms.RandomHorizontalFlip(
        p=0.5
    ),
    transforms.RandomVerticalFlip(
        p=0.2
    ),
    transforms.RandomRotation(
        degrees=15
    ),
    transforms.ColorJitter(
        brightness=0.15,
        contrast=0.15,
        saturation=0.10,
        hue=0.02
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


eval_transform = transforms.Compose([
    transforms.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


print("DERM7PT IMAGE TRANSFORMS RESTORATION")

print("\nImage size:")
print(f"{IMAGE_SIZE} × {IMAGE_SIZE}")

print("\nTraining augmentation:")
print("Horizontal flip")
print("Vertical flip")
print("Rotation")
print("Color jitter")

print("\nValidation/Test:")
print("Resize + normalization only")

print("✅ IMAGE TRANSFORMS RESTORED")

DERM7PT IMAGE TRANSFORMS RESTORATION

Image size:
224 × 224

Training augmentation:
Horizontal flip
Vertical flip
Rotation
Color jitter

Validation/Test:
Resize + normalization only
✅ IMAGE TRANSFORMS RESTORED

In [11]:
# DERM7PT TRANSFORMED DATASET RESTORATION
# Purpose: Attach the fixed training and evaluation transforms
#          to the Derm7pt train, validation, and test datasets.

train_dataset = Derm7ptDataset(
    train_df,
    IMAGE_ROOT,
    transform=train_transform
)

val_dataset = Derm7ptDataset(
    val_df,
    IMAGE_ROOT,
    transform=eval_transform
)

test_dataset = Derm7ptDataset(
    test_df,
    IMAGE_ROOT,
    transform=eval_transform
)


train_sample, train_label = train_dataset[0]
val_sample, val_label = val_dataset[0]
test_sample, test_label = test_dataset[0]


print("DERM7PT TRANSFORMED DATASET RESTORATION")

print("\nTraining samples:")
print(len(train_dataset))

print("\nValidation samples:")
print(len(val_dataset))

print("\nTest samples:")
print(len(test_dataset))

print("\nTraining tensor shape:")
print(train_sample.shape)

print("\nValidation tensor shape:")
print(val_sample.shape)

print("\nTest tensor shape:")
print(test_sample.shape)

print("\nTensor dtype:")
print(train_sample.dtype)

print("✅ TRANSFORMED DATASETS RESTORED")

DERM7PT TRANSFORMED DATASET RESTORATION

Training samples:
413

Validation samples:
203

Test samples:
395

Training tensor shape:
torch.Size([3, 224, 224])

Validation tensor shape:
torch.Size([3, 224, 224])

Test tensor shape:
torch.Size([3, 224, 224])

Tensor dtype:
torch.float32
✅ TRANSFORMED DATASETS RESTORED

In [12]:
# DERM7PT DATALOADER RESTORATION
# Purpose: Rebuild the GPU-ready DataLoaders for the frozen
#          Derm7pt train, validation, and test splits.

from torch.utils.data import DataLoader


BATCH_SIZE = 32
NUM_WORKERS = 2


train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    drop_last=False
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    drop_last=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    drop_last=False
)


print("DERM7PT DATALOADER RESTORATION")

print("\nBatch size:")
print(BATCH_SIZE)

print("\nNumber of workers:")
print(NUM_WORKERS)

print("\nPin memory:")
print(True)

print("\nTraining batches:")
print(len(train_loader))

print("\nValidation batches:")
print(len(val_loader))

print("\nTest batches:")
print(len(test_loader))

print("✅ DATALOADERS RESTORED")

DERM7PT DATALOADER RESTORATION

Batch size:
32

Number of workers:
2

Pin memory:
True

Training batches:
13

Validation batches:
7

Test batches:
13
✅ DATALOADERS RESTORED

In [13]:
# DERM7PT TRAINING CONFIGURATION RESTORATION
# Purpose: Restore the class weights, device, and fixed training
#          configuration used for comparable Derm7pt experiments.

import torch
import torch.nn as nn


DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)


class_counts = (
    train_df["binary_label"]
    .value_counts()
)


non_melanoma_count = int(
    class_counts["Non-Melanoma"]
)

melanoma_count = int(
    class_counts["Melanoma"]
)


total_samples = (
    non_melanoma_count
    + melanoma_count
)


class_weights = torch.tensor(
    [
        total_samples
        / (2 * non_melanoma_count),

        total_samples
        / (2 * melanoma_count)
    ],
    dtype=torch.float32,
    device=DEVICE
)


criterion = nn.CrossEntropyLoss(
    weight=class_weights
)


EPOCHS = 20
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-5


print("DERM7PT TRAINING CONFIGURATION RESTORATION")

print("\nDevice:")
print(DEVICE)

print("\nGPU count:")
print(torch.cuda.device_count())

print("\nTraining samples:")
print(total_samples)

print("\nNon-Melanoma:")
print(non_melanoma_count)

print("\nMelanoma:")
print(melanoma_count)

print("\nClass weights:")
print(
    class_weights.cpu().numpy()
)

print("\nEpochs:")
print(EPOCHS)

print("\nLearning rate:")
print(LEARNING_RATE)

print("\nWeight decay:")
print(WEIGHT_DECAY)

print("\nLoss:")
print("Weighted CrossEntropyLoss")

print("✅ TRAINING CONFIGURATION RESTORED")

DERM7PT TRAINING CONFIGURATION RESTORATION

Device:
cuda

GPU count:
2

Training samples:
413

Non-Melanoma:
323

Melanoma:
90

Class weights:
[0.6393189 2.2944446]

Epochs:
20

Learning rate:
0.0001

Weight decay:
1e-05

Loss:
Weighted CrossEntropyLoss
✅ TRAINING CONFIGURATION RESTORED

In [14]:
# DERM7PT EFFICIENTNET-B0 BASELINE
# Purpose: Define the second Derm7pt binary classification
#          baseline with a two-class output layer.

import torch
import torch.nn as nn
from torchvision.models import efficientnet_b0


efficientnet_model = efficientnet_b0(
    weights=None
)

num_features = (
    efficientnet_model.classifier[-1].in_features
)

efficientnet_model.classifier[-1] = nn.Linear(
    num_features,
    2
)


efficientnet_model = efficientnet_model.to(
    DEVICE
)


print("DERM7PT EFFICIENTNET-B0 BASELINE")

print("\nModel:")
print("EfficientNet-B0")

print("\nInput:")
print("(batch, 3, 224, 224)")

print("\nOutput:")
print("(batch, 2)")

print("\nParameters:")
print(
    f"{sum(p.numel() for p in efficientnet_model.parameters()):,}"
)

print("\nModel device:")
print(
    next(efficientnet_model.parameters()).device
)

print("✅ EFFICIENTNET-B0 ARCHITECTURE DEFINED")

DERM7PT EFFICIENTNET-B0 BASELINE

Model:
EfficientNet-B0

Input:
(batch, 3, 224, 224)

Output:
(batch, 2)

Parameters:
4,010,110

Model device:
cuda:0
✅ EFFICIENTNET-B0 ARCHITECTURE DEFINED

In [15]:
# DERM7PT EFFICIENTNET-B0 GPU FORWARD PASS TEST
# Purpose: Verify that EfficientNet-B0 correctly processes a
#          real Derm7pt batch on the available T4 GPU.

import torch


efficientnet_model.eval()


images, labels = next(
    iter(train_loader)
)


images = images.to(
    DEVICE,
    non_blocking=True
)

labels = labels.to(
    DEVICE,
    non_blocking=True
)


with torch.no_grad():

    outputs = efficientnet_model(
        images
    )


print("DERM7PT EFFICIENTNET-B0 GPU FORWARD PASS TEST")

print("\nInput image shape:")
print(tuple(images.shape))

print("\nGround-truth label shape:")
print(tuple(labels.shape))

print("\nModel output shape:")
print(tuple(outputs.shape))

print("\nModel device:")
print(
    next(
        efficientnet_model.parameters()
    ).device
)

print("\nOutput dtype:")
print(outputs.dtype)

print("\nOutput value range:")

print(
    "Minimum:",
    outputs.min().item()
)

print(
    "Maximum:",
    outputs.max().item()
)



if outputs.shape == (
    images.shape[0],
    2
):

    print(
        "✅ EFFICIENTNET-B0 GPU FORWARD PASS TEST PASSED"
    )

else:

    print(
        "❌ EFFICIENTNET-B0 FORWARD PASS FAILED"
    )

DERM7PT EFFICIENTNET-B0 GPU FORWARD PASS TEST

Input image shape:
(32, 3, 224, 224)

Ground-truth label shape:
(32,)

Model output shape:
(32, 2)

Model device:
cuda:0

Output dtype:
torch.float32

Output value range:
Minimum: 0.020964840427041054
Maximum: 0.02334817312657833
✅ EFFICIENTNET-B0 GPU FORWARD PASS TEST PASSED

In [16]:
# DERM7PT EFFICIENTNET-B0 TRAINING SETUP
# Purpose: Configure the optimizer, weighted loss, multi-GPU
#          execution, and mixed-precision training components.

import torch
import torch.nn as nn
import torch.optim as optim


if torch.cuda.device_count() > 1:

    efficientnet_model = nn.DataParallel(
        efficientnet_model
    )


efficientnet_model = efficientnet_model.to(
    DEVICE
)


efficientnet_optimizer = optim.Adam(
    efficientnet_model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY
)


efficientnet_criterion = nn.CrossEntropyLoss(
    weight=class_weights
)


efficientnet_scaler = torch.amp.GradScaler(
    "cuda"
)


print("DERM7PT EFFICIENTNET-B0 TRAINING SETUP")

print("\nParameters:")
print(
    f"{sum(p.numel() for p in efficientnet_model.parameters()):,}"
)

print("\nDevice:")
print(
    next(
        efficientnet_model.parameters()
    ).device
)

print("\nMulti-GPU:")
print(
    isinstance(
        efficientnet_model,
        nn.DataParallel
    )
)

print("\nOptimizer:")
print("Adam")

print("\nLoss:")
print("Weighted CrossEntropyLoss")

print("\nMixed precision:")
print("Enabled")

print("✅ EFFICIENTNET-B0 TRAINING SETUP READY")

DERM7PT EFFICIENTNET-B0 TRAINING SETUP

Parameters:
4,010,110

Device:
cuda:0

Multi-GPU:
True

Optimizer:
Adam

Loss:
Weighted CrossEntropyLoss

Mixed precision:
Enabled
✅ EFFICIENTNET-B0 TRAINING SETUP READY

In [18]:
# DERM7PT EFFICIENTNET-B0 SINGLE-BATCH TRAINING TEST
# Purpose: Verify one complete AMP + multi-GPU optimization
#          step before launching the full EfficientNet-B0 run.

import time
import torch


efficientnet_model.train()


images, labels = next(
    iter(train_loader)
)


images = images.to(
    DEVICE,
    non_blocking=True
)

labels = labels.to(
    DEVICE,
    non_blocking=True
)


efficientnet_optimizer.zero_grad(
    set_to_none=True
)


if torch.cuda.is_available():
    torch.cuda.synchronize()

start_time = time.time()


with torch.amp.autocast(
    device_type="cuda"
):

    outputs = efficientnet_model(
        images
    )

    loss = efficientnet_criterion(
        outputs,
        labels
    )


efficientnet_scaler.scale(
    loss
).backward()


efficientnet_scaler.step(
    efficientnet_optimizer
)

efficientnet_scaler.update()


if torch.cuda.is_available():
    torch.cuda.synchronize()

elapsed_time = (
    time.time() - start_time
)


predictions = torch.argmax(
    outputs,
    dim=1
)


accuracy = (
    predictions == labels
).float().mean().item()


print("DERM7PT EFFICIENTNET-B0 SINGLE-BATCH TRAINING TEST")

print("\nBatch image shape:")
print(tuple(images.shape))

print("\nBatch label shape:")
print(tuple(labels.shape))

print("\nOutput shape:")
print(tuple(outputs.shape))

print("\nLoss:")
print(f"{loss.item():.6f}")

print("\nBatch accuracy:")
print(f"{accuracy:.6f}")

print("\nTraining step time:")
print(f"{elapsed_time:.2f} seconds")

print("\nGPU memory allocated:")
print(
    f"{torch.cuda.memory_allocated() / (1024 ** 3):.2f} GB"
)

print("\nMulti-GPU:")
print(
    isinstance(
        efficientnet_model,
        torch.nn.DataParallel
    )
)

print("\nMixed precision:")
print("Enabled")


if (
    outputs.shape == (images.shape[0], 2)
    and isinstance(
        efficientnet_model,
        torch.nn.DataParallel
    )
):

    print(
        "✅ EFFICIENTNET-B0 TRAINING TEST PASSED"
    )

else:

    print(
        "❌ EFFICIENTNET-B0 TRAINING TEST FAILED"
    )

DERM7PT EFFICIENTNET-B0 SINGLE-BATCH TRAINING TEST

Batch image shape:
(32, 3, 224, 224)

Batch label shape:
(32,)

Output shape:
(32, 2)

Loss:
0.720648

Batch accuracy:
0.156250

Training step time:
3.64 seconds

GPU memory allocated:
0.11 GB

Multi-GPU:
True

Mixed precision:
Enabled
✅ EFFICIENTNET-B0 TRAINING TEST PASSED

In [20]:
# DERM7PT EFFICIENTNET-B0 CLEAN BASELINE INITIALIZATION
# Purpose: Reinitialize EfficientNet-B0 and all training
#          components so the recorded baseline starts from scratch.

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision.models import efficientnet_b0


efficientnet_model = efficientnet_b0(
    weights=None
)

num_features = (
    efficientnet_model.classifier[-1].in_features
)

efficientnet_model.classifier[-1] = nn.Linear(
    num_features,
    2
)


if torch.cuda.device_count() > 1:

    efficientnet_model = nn.DataParallel(
        efficientnet_model
    )


efficientnet_model = efficientnet_model.to(
    DEVICE
)


efficientnet_optimizer = optim.Adam(
    efficientnet_model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY
)


efficientnet_criterion = nn.CrossEntropyLoss(
    weight=class_weights
)


efficientnet_scaler = torch.amp.GradScaler(
    "cuda"
)


parameter_count = sum(
    p.numel()
    for p in efficientnet_model.parameters()
)


print("DERM7PT EFFICIENTNET-B0 CLEAN BASELINE INITIALIZATION")

print("\nModel:")
print("EfficientNet-B0")

print("\nParameters:")
print(f"{parameter_count:,}")

print("\nDevice:")
print(DEVICE)

print("\nGPU count:")
print(torch.cuda.device_count())

print("\nMulti-GPU:")
print(
    isinstance(
        efficientnet_model,
        nn.DataParallel
    )
)

print("\nMixed precision:")
print("Enabled")

print("\nOptimizer:")
print("Adam")

print("\nLoss:")
print("Weighted CrossEntropyLoss")

print("\nTraining state:")
print("FRESH INITIALIZATION")

print("✅ CLEAN EFFICIENTNET-B0 BASELINE READY")

DERM7PT EFFICIENTNET-B0 CLEAN BASELINE INITIALIZATION

Model:
EfficientNet-B0

Parameters:
4,010,110

Device:
cuda

GPU count:
2

Multi-GPU:
True

Mixed precision:
Enabled

Optimizer:
Adam

Loss:
Weighted CrossEntropyLoss

Training state:
FRESH INITIALIZATION
✅ CLEAN EFFICIENTNET-B0 BASELINE READY

In [21]:
# DERM7PT EFFICIENTNET-B0 BASELINE TRAINING
# Purpose: Train the clean EfficientNet-B0 baseline for 20
#          epochs with validation monitoring and checkpointing.

import os
import time
import numpy as np
import torch
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


EFFICIENTNET_BEST_PATH = (
    "/kaggle/working/"
    "derm7pt_efficientnet_b0_best.pth"
)

EFFICIENTNET_HISTORY_PATH = (
    "/kaggle/working/"
    "derm7pt_efficientnet_b0_training_history.pt"
)


efficientnet_history = {
    "train_loss": [],
    "val_loss": [],
    "val_accuracy": [],
    "val_precision": [],
    "val_recall": [],
    "val_f1": [],
    "val_roc_auc": []
}


best_efficientnet_f1 = -1.0
best_efficientnet_epoch = 0


def evaluate_efficientnet(
    model,
    loader
):

    model.eval()

    total_loss = 0.0

    all_labels = []
    all_predictions = []
    all_probabilities = []


    with torch.no_grad():

        for images, labels in loader:

            images = images.to(
                DEVICE,
                non_blocking=True
            )

            labels = labels.to(
                DEVICE,
                non_blocking=True
            )


            with torch.amp.autocast(
                device_type="cuda"
            ):

                outputs = model(
                    images
                )

                loss = efficientnet_criterion(
                    outputs,
                    labels
                )


            probabilities = torch.softmax(
                outputs.float(),
                dim=1
            )[:, 1]


            predictions = torch.argmax(
                outputs,
                dim=1
            )


            total_loss += (
                loss.item()
                * images.size(0)
            )


            all_labels.extend(
                labels.cpu().numpy()
            )

            all_predictions.extend(
                predictions.cpu().numpy()
            )

            all_probabilities.extend(
                probabilities.cpu().numpy()
            )


    all_labels = np.array(
        all_labels
    )

    all_predictions = np.array(
        all_predictions
    )

    all_probabilities = np.array(
        all_probabilities
    )


    average_loss = (
        total_loss
        / len(loader.dataset)
    )


    accuracy = accuracy_score(
        all_labels,
        all_predictions
    )

    precision = precision_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    recall = recall_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    f1 = f1_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        all_labels,
        all_probabilities
    )


    return (
        average_loss,
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    )


print("DERM7PT EFFICIENTNET-B0 BASELINE TRAINING")

print(
    f"\nTraining for {EPOCHS} epochs..."
)


training_start = time.time()


for epoch in range(
    1,
    EPOCHS + 1
):

    epoch_start = time.time()

    efficientnet_model.train()

    running_loss = 0.0


    for images, labels in train_loader:

        images = images.to(
            DEVICE,
            non_blocking=True
        )

        labels = labels.to(
            DEVICE,
            non_blocking=True
        )


        efficientnet_optimizer.zero_grad(
            set_to_none=True
        )


        with torch.amp.autocast(
            device_type="cuda"
        ):

            outputs = efficientnet_model(
                images
            )

            loss = efficientnet_criterion(
                outputs,
                labels
            )


        efficientnet_scaler.scale(
            loss
        ).backward()


        efficientnet_scaler.step(
            efficientnet_optimizer
        )

        efficientnet_scaler.update()


        running_loss += (
            loss.item()
            * images.size(0)
        )


    train_loss = (
        running_loss
        / len(train_loader.dataset)
    )


    (
        val_loss,
        val_accuracy,
        val_precision,
        val_recall,
        val_f1,
        val_roc_auc
    ) = evaluate_efficientnet(
        efficientnet_model,
        val_loader
    )


    efficientnet_history[
        "train_loss"
    ].append(
        train_loss
    )

    efficientnet_history[
        "val_loss"
    ].append(
        val_loss
    )

    efficientnet_history[
        "val_accuracy"
    ].append(
        val_accuracy
    )

    efficientnet_history[
        "val_precision"
    ].append(
        val_precision
    )

    efficientnet_history[
        "val_recall"
    ].append(
        val_recall
    )

    efficientnet_history[
        "val_f1"
    ].append(
        val_f1
    )

    efficientnet_history[
        "val_roc_auc"
    ].append(
        val_roc_auc
    )


    epoch_time = (
        time.time()
        - epoch_start
    )


    is_best = (
        val_f1
        > best_efficientnet_f1
    )


    if is_best:

        best_efficientnet_f1 = val_f1
        best_efficientnet_epoch = epoch

        torch.save(
            efficientnet_model.state_dict(),
            EFFICIENTNET_BEST_PATH
        )


    marker = (
        " ⭐ BEST"
        if is_best
        else ""
    )


    print(
        f"Epoch {epoch:02d}/{EPOCHS} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f} | "
        f"Val Acc: {val_accuracy:.4f} | "
        f"Val Precision: {val_precision:.4f} | "
        f"Val Recall: {val_recall:.4f} | "
        f"Val F1: {val_f1:.4f} | "
        f"Val AUC: {val_roc_auc:.4f} | "
        f"Time: {epoch_time / 60:.2f} min"
        f"{marker}"
    )


total_training_time = (
    time.time()
    - training_start
)


torch.save(
    efficientnet_history,
    EFFICIENTNET_HISTORY_PATH
)


print(
    "DERM7PT EFFICIENTNET-B0 BASELINE TRAINING COMPLETED"
)

print("\nBest validation F1:")
print(
    f"{best_efficientnet_f1:.6f}"
)

print("\nBest epoch:")
print(
    best_efficientnet_epoch
)

print("\nBest model:")
print(
    EFFICIENTNET_BEST_PATH
)

print("\nTraining history:")
print(
    EFFICIENTNET_HISTORY_PATH
)

print("\nTotal training time:")
print(
    f"{total_training_time / 60:.2f} minutes"
)

DERM7PT EFFICIENTNET-B0 BASELINE TRAINING

Training for 20 epochs...
Epoch 01/20 | Train Loss: 0.7088 | Val Loss: 0.7159 | Val Acc: 0.3005 | Val Precision: 0.3005 | Val Recall: 1.0000 | Val F1: 0.4621 | Val AUC: 0.4502 | Time: 1.41 min ⭐ BEST
Epoch 02/20 | Train Loss: 0.7050 | Val Loss: 0.7059 | Val Acc: 0.3005 | Val Precision: 0.3005 | Val Recall: 1.0000 | Val F1: 0.4621 | Val AUC: 0.5592 | Time: 1.28 min
Epoch 03/20 | Train Loss: 0.6858 | Val Loss: 0.7026 | Val Acc: 0.3005 | Val Precision: 0.3005 | Val Recall: 1.0000 | Val F1: 0.4621 | Val AUC: 0.5449 | Time: 1.28 min
Epoch 04/20 | Train Loss: 0.6778 | Val Loss: 0.6783 | Val Acc: 0.6995 | Val Precision: 0.0000 | Val Recall: 0.0000 | Val F1: 0.0000 | Val AUC: 0.7321 | Time: 1.28 min
Epoch 05/20 | Train Loss: 0.6576 | Val Loss: 0.6491 | Val Acc: 0.6995 | Val Precision: 0.0000 | Val Recall: 0.0000 | Val F1: 0.0000 | Val AUC: 0.7628 | Time: 1.29 min
Epoch 06/20 | Train Loss: 0.6782 | Val Loss: 0.6172 | Val Acc: 0.7241 | Val Precision: 0.7273 | Val Recall: 0.1311 | Val F1: 0.2222 | Val AUC: 0.7740 | Time: 1.29 min
Epoch 07/20 | Train Loss: 0.6149 | Val Loss: 0.6024 | Val Acc: 0.6847 | Val Precision: 0.4831 | Val Recall: 0.7049 | Val F1: 0.5733 | Val AUC: 0.7673 | Time: 1.29 min ⭐ BEST
Epoch 08/20 | Train Loss: 0.6256 | Val Loss: 0.6282 | Val Acc: 0.6847 | Val Precision: 0.4862 | Val Recall: 0.8689 | Val F1: 0.6235 | Val AUC: 0.7622 | Time: 1.29 min ⭐ BEST
Epoch 09/20 | Train Loss: 0.6278 | Val Loss: 0.6097 | Val Acc: 0.6305 | Val Precision: 0.4340 | Val Recall: 0.7541 | Val F1: 0.5509 | Val AUC: 0.7446 | Time: 1.30 min
Epoch 10/20 | Train Loss: 0.6291 | Val Loss: 0.5736 | Val Acc: 0.6798 | Val Precision: 0.4778 | Val Recall: 0.7049 | Val F1: 0.5695 | Val AUC: 0.7689 | Time: 1.31 min
Epoch 11/20 | Train Loss: 0.6065 | Val Loss: 0.5730 | Val Acc: 0.6847 | Val Precision: 0.4839 | Val Recall: 0.7377 | Val F1: 0.5844 | Val AUC: 0.7678 | Time: 1.31 min
Epoch 12/20 | Train Loss: 0.6112 | Val Loss: 0.6309 | Val Acc: 0.6207 | Val Precision: 0.4333 | Val Recall: 0.8525 | Val F1: 0.5746 | Val AUC: 0.7562 | Time: 1.32 min
Epoch 13/20 | Train Loss: 0.5804 | Val Loss: 0.6008 | Val Acc: 0.6256 | Val Precision: 0.4286 | Val Recall: 0.7377 | Val F1: 0.5422 | Val AUC: 0.7585 | Time: 1.34 min
Epoch 14/20 | Train Loss: 0.5841 | Val Loss: 0.5719 | Val Acc: 0.6749 | Val Precision: 0.4719 | Val Recall: 0.6885 | Val F1: 0.5600 | Val AUC: 0.7573 | Time: 1.33 min
Epoch 15/20 | Train Loss: 0.5936 | Val Loss: 0.5779 | Val Acc: 0.6847 | Val Precision: 0.4819 | Val Recall: 0.6557 | Val F1: 0.5556 | Val AUC: 0.7608 | Time: 1.32 min
Epoch 16/20 | Train Loss: 0.5622 | Val Loss: 0.6096 | Val Acc: 0.6847 | Val Precision: 0.4824 | Val Recall: 0.6721 | Val F1: 0.5616 | Val AUC: 0.7265 | Time: 1.33 min
Epoch 17/20 | Train Loss: 0.6036 | Val Loss: 0.6381 | Val Acc: 0.5961 | Val Precision: 0.4054 | Val Recall: 0.7377 | Val F1: 0.5233 | Val AUC: 0.7411 | Time: 1.33 min
Epoch 18/20 | Train Loss: 0.5849 | Val Loss: 0.5844 | Val Acc: 0.6798 | Val Precision: 0.4737 | Val Recall: 0.5902 | Val F1: 0.5255 | Val AUC: 0.7466 | Time: 1.32 min
Epoch 19/20 | Train Loss: 0.5827 | Val Loss: 0.6532 | Val Acc: 0.6256 | Val Precision: 0.4286 | Val Recall: 0.7377 | Val F1: 0.5422 | Val AUC: 0.7265 | Time: 1.33 min
Epoch 20/20 | Train Loss: 0.5370 | Val Loss: 0.6916 | Val Acc: 0.6158 | Val Precision: 0.4220 | Val Recall: 0.7541 | Val F1: 0.5412 | Val AUC: 0.7389 | Time: 1.33 min
DERM7PT EFFICIENTNET-B0 BASELINE TRAINING COMPLETED

Best validation F1:
0.623529

Best epoch:
8

Best model:
/kaggle/working/derm7pt_efficientnet_b0_best.pth

Training history:
/kaggle/working/derm7pt_efficientnet_b0_training_history.pt

Total training time:
26.29 minutes

In [22]:
# DERM7PT EFFICIENTNET-B0 BASELINE RESULTS SAVE
# Purpose: Permanently record the best validation performance
#          and training configuration before final test evaluation.

import json


efficientnet_baseline_results = {
    "dataset": "Derm7pt",
    "task": "Binary Classification",
    "input_modality": "Dermoscopic",
    "model": "EfficientNet-B0",

    "parameters": 4010110,

    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "learning_rate": LEARNING_RATE,
    "weight_decay": WEIGHT_DECAY,

    "loss": "Weighted CrossEntropyLoss",
    "optimizer": "Adam",
    "mixed_precision": True,
    "multi_gpu": True,

    "best_epoch": best_efficientnet_epoch,

    "best_validation_f1": (
        efficientnet_history["val_f1"][
            best_efficientnet_epoch - 1
        ]
    ),

    "validation_accuracy_at_best": (
        efficientnet_history["val_accuracy"][
            best_efficientnet_epoch - 1
        ]
    ),

    "validation_precision_at_best": (
        efficientnet_history["val_precision"][
            best_efficientnet_epoch - 1
        ]
    ),

    "validation_recall_at_best": (
        efficientnet_history["val_recall"][
            best_efficientnet_epoch - 1
        ]
    ),

    "validation_roc_auc_at_best": (
        efficientnet_history["val_roc_auc"][
            best_efficientnet_epoch - 1
        ]
    ),

    "validation_loss_at_best": (
        efficientnet_history["val_loss"][
            best_efficientnet_epoch - 1
        ]
    ),

    "best_model_path": EFFICIENTNET_BEST_PATH,
    "training_history_path": EFFICIENTNET_HISTORY_PATH
}


EFFICIENTNET_RESULTS_PATH = (
    "/kaggle/working/"
    "derm7pt_efficientnet_b0_baseline_results.json"
)


with open(
    EFFICIENTNET_RESULTS_PATH,
    "w"
) as f:

    json.dump(
        efficientnet_baseline_results,
        f,
        indent=4
    )


print("DERM7PT EFFICIENTNET-B0 BASELINE RESULTS SAVED")

print("\nResults file:")
print(EFFICIENTNET_RESULTS_PATH)

print("\nBest epoch:")
print(best_efficientnet_epoch)

print("\nBest validation F1:")
print(
    f"{efficientnet_baseline_results['best_validation_f1']:.6f}"
)

print("\nValidation Accuracy:")
print(
    f"{efficientnet_baseline_results['validation_accuracy_at_best']:.6f}"
)

print("\nValidation Precision:")
print(
    f"{efficientnet_baseline_results['validation_precision_at_best']:.6f}"
)

print("\nValidation Recall:")
print(
    f"{efficientnet_baseline_results['validation_recall_at_best']:.6f}"
)

print("\nValidation ROC-AUC:")
print(
    f"{efficientnet_baseline_results['validation_roc_auc_at_best']:.6f}"
)

print("✅ EFFICIENTNET-B0 BASELINE RESULTS RECORDED")

DERM7PT EFFICIENTNET-B0 BASELINE RESULTS SAVED

Results file:
/kaggle/working/derm7pt_efficientnet_b0_baseline_results.json

Best epoch:
8

Best validation F1:
0.623529

Validation Accuracy:
0.684729

Validation Precision:
0.486239

Validation Recall:
0.868852

Validation ROC-AUC:
0.762180
✅ EFFICIENTNET-B0 BASELINE RESULTS RECORDED

In [23]:
# DERM7PT EFFICIENTNET-B0 ARTIFACT VERIFICATION
# Purpose: Verify the trained checkpoint, training history,
#          and baseline results before final test evaluation.

import os


EFFICIENTNET_ARTIFACTS = {
    "Best model": EFFICIENTNET_BEST_PATH,
    "Training history": EFFICIENTNET_HISTORY_PATH,
    "Baseline results": EFFICIENTNET_RESULTS_PATH
}


print("DERM7PT EFFICIENTNET-B0 ARTIFACT VERIFICATION")


all_verified = True


for name, path in EFFICIENTNET_ARTIFACTS.items():

    exists = os.path.exists(path)

    print(f"\n{name}:")
    print(path)

    print("Exists:")
    print(exists)

    if exists:

        size_mb = (
            os.path.getsize(path)
            / (1024 ** 2)
        )

        print(
            f"Size: {size_mb:.2f} MB"
        )

    else:

        all_verified = False



if all_verified:

    print(
        "✅ ALL EFFICIENTNET-B0 ARTIFACTS VERIFIED"
    )

else:

    print(
        "❌ SOME EFFICIENTNET-B0 ARTIFACTS ARE MISSING"
    )

DERM7PT EFFICIENTNET-B0 ARTIFACT VERIFICATION

Best model:
/kaggle/working/derm7pt_efficientnet_b0_best.pth
Exists:
True
Size: 15.59 MB

Training history:
/kaggle/working/derm7pt_efficientnet_b0_training_history.pt
Exists:
True
Size: 0.00 MB

Baseline results:
/kaggle/working/derm7pt_efficientnet_b0_baseline_results.json
Exists:
True
Size: 0.00 MB
✅ ALL EFFICIENTNET-B0 ARTIFACTS VERIFIED

In [24]:
# DERM7PT BEST EFFICIENTNET-B0 CHECKPOINT LOADING
# Purpose: Load the saved best-validation EfficientNet-B0
#          checkpoint into a fresh model for final testing.

import torch
import torch.nn as nn
from torchvision.models import efficientnet_b0


best_efficientnet_model = efficientnet_b0(
    weights=None
)

num_features = (
    best_efficientnet_model.classifier[-1].in_features
)

best_efficientnet_model.classifier[-1] = nn.Linear(
    num_features,
    2
)


if torch.cuda.device_count() > 1:

    best_efficientnet_model = nn.DataParallel(
        best_efficientnet_model
    )


best_efficientnet_model = (
    best_efficientnet_model.to(DEVICE)
)


efficientnet_checkpoint = torch.load(
    EFFICIENTNET_BEST_PATH,
    map_location=DEVICE,
    weights_only=True
)


best_efficientnet_model.load_state_dict(
    efficientnet_checkpoint
)


best_efficientnet_model.eval()


print("DERM7PT BEST EFFICIENTNET-B0 CHECKPOINT LOADING")

print("\nCheckpoint:")
print(EFFICIENTNET_BEST_PATH)

print("\nBest epoch:")
print(best_efficientnet_epoch)

print("\nModel parameters:")
print(
    f"{sum(p.numel() for p in best_efficientnet_model.parameters()):,}"
)

print("\nDevice:")
print(
    next(
        best_efficientnet_model.parameters()
    ).device
)

print("\nMulti-GPU:")
print(
    isinstance(
        best_efficientnet_model,
        nn.DataParallel
    )
)

print("\nModel mode:")
print(
    "Evaluation"
    if not best_efficientnet_model.training
    else "Training"
)

print("✅ BEST EFFICIENTNET-B0 CHECKPOINT LOADED")

DERM7PT BEST EFFICIENTNET-B0 CHECKPOINT LOADING

Checkpoint:
/kaggle/working/derm7pt_efficientnet_b0_best.pth

Best epoch:
8

Model parameters:
4,010,110

Device:
cuda:0

Multi-GPU:
True

Model mode:
Evaluation
✅ BEST EFFICIENTNET-B0 CHECKPOINT LOADED

In [25]:
# DERM7PT EFFICIENTNET-B0 FINAL TEST SET EVALUATION
# Purpose: Evaluate the saved best-validation checkpoint on the
#          untouched Derm7pt test set and calculate final metrics.

import time
import numpy as np
import torch
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)


best_efficientnet_model.eval()


all_labels = []
all_predictions = []
all_probabilities = []

total_test_loss = 0.0


if torch.cuda.is_available():
    torch.cuda.synchronize()

evaluation_start = time.time()


with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(
            DEVICE,
            non_blocking=True
        )

        labels = labels.to(
            DEVICE,
            non_blocking=True
        )


        with torch.amp.autocast(
            device_type="cuda"
        ):

            outputs = best_efficientnet_model(
                images
            )

            loss = efficientnet_criterion(
                outputs,
                labels
            )


        probabilities = torch.softmax(
            outputs.float(),
            dim=1
        )[:, 1]


        predictions = torch.argmax(
            outputs,
            dim=1
        )


        total_test_loss += (
            loss.item()
            * images.size(0)
        )


        all_labels.extend(
            labels.cpu().numpy()
        )

        all_predictions.extend(
            predictions.cpu().numpy()
        )

        all_probabilities.extend(
            probabilities.cpu().numpy()
        )


if torch.cuda.is_available():
    torch.cuda.synchronize()


evaluation_time = (
    time.time()
    - evaluation_start
)


all_labels = np.array(
    all_labels
)

all_predictions = np.array(
    all_predictions
)

all_probabilities = np.array(
    all_probabilities
)


test_loss = (
    total_test_loss
    / len(test_loader.dataset)
)


test_accuracy = accuracy_score(
    all_labels,
    all_predictions
)

test_precision = precision_score(
    all_labels,
    all_predictions,
    zero_division=0
)

test_recall = recall_score(
    all_labels,
    all_predictions,
    zero_division=0
)

test_f1 = f1_score(
    all_labels,
    all_predictions,
    zero_division=0
)

test_roc_auc = roc_auc_score(
    all_labels,
    all_probabilities
)


cm = confusion_matrix(
    all_labels,
    all_predictions
)


average_time_per_image = (
    evaluation_time
    / len(test_loader.dataset)
)


print("DERM7PT EFFICIENTNET-B0 FINAL TEST SET EVALUATION")

print("\nTest samples:")
print(len(test_loader.dataset))

print("\nTest loss:")
print(f"{test_loss:.6f}")

print("\nTest Accuracy:")
print(f"{test_accuracy:.6f}")

print("\nTest Precision:")
print(f"{test_precision:.6f}")

print("\nTest Recall / Sensitivity:")
print(f"{test_recall:.6f}")

print("\nTest F1:")
print(f"{test_f1:.6f}")

print("\nTest ROC-AUC:")
print(f"{test_roc_auc:.6f}")

print("\nConfusion Matrix:")
print(cm)

print("\nTotal evaluation time:")
print(f"{evaluation_time / 60:.2f} minutes")

print("\nAverage time per test image:")
print(f"{average_time_per_image:.4f} seconds")

print("✅ EFFICIENTNET-B0 TEST EVALUATION COMPLETED")

DERM7PT EFFICIENTNET-B0 FINAL TEST SET EVALUATION

Test samples:
395

Test loss:
0.633448

Test Accuracy:
0.658228

Test Precision:
0.403409

Test Recall / Sensitivity:
0.702970

Test F1:
0.512635

Test ROC-AUC:
0.742844

Confusion Matrix:
[[189 105]
 [ 30  71]]

Total evaluation time:
0.84 minutes

Average time per test image:
0.1279 seconds
✅ EFFICIENTNET-B0 TEST EVALUATION COMPLETED

In [26]:
# DERM7PT EFFICIENTNET-B0 FINAL RESULTS SAVE
# Purpose: Permanently record the untouched test-set performance
#          of the best-validation EfficientNet-B0 checkpoint.

import json


efficientnet_final_results = {
    "dataset": "Derm7pt",
    "task": "Binary Classification",
    "input_modality": "Dermoscopic",
    "model": "EfficientNet-B0",

    "parameters": 4010110,

    "best_epoch": best_efficientnet_epoch,

    "test_samples": len(test_loader.dataset),

    "test_loss": test_loss,
    "test_accuracy": test_accuracy,
    "test_precision": test_precision,
    "test_recall": test_recall,
    "test_f1": test_f1,
    "test_roc_auc": test_roc_auc,

    "confusion_matrix": cm.tolist(),

    "evaluation_time_seconds": evaluation_time,
    "average_time_per_test_image_seconds": average_time_per_image,

    "best_model_path": EFFICIENTNET_BEST_PATH,
    "training_history_path": EFFICIENTNET_HISTORY_PATH,
    "baseline_results_path": EFFICIENTNET_RESULTS_PATH
}


EFFICIENTNET_FINAL_RESULTS_PATH = (
    "/kaggle/working/"
    "derm7pt_efficientnet_b0_final_results.json"
)


with open(
    EFFICIENTNET_FINAL_RESULTS_PATH,
    "w"
) as f:

    json.dump(
        efficientnet_final_results,
        f,
        indent=4
    )


print("DERM7PT EFFICIENTNET-B0 FINAL RESULTS SAVED")

print("\nFinal results file:")
print(EFFICIENTNET_FINAL_RESULTS_PATH)

print("\nTest Accuracy:")
print(f"{test_accuracy:.6f}")

print("\nTest Precision:")
print(f"{test_precision:.6f}")

print("\nTest Recall:")
print(f"{test_recall:.6f}")

print("\nTest F1:")
print(f"{test_f1:.6f}")

print("\nTest ROC-AUC:")
print(f"{test_roc_auc:.6f}")

print("✅ FINAL TEST RESULTS SAFELY RECORDED")

DERM7PT EFFICIENTNET-B0 FINAL RESULTS SAVED

Final results file:
/kaggle/working/derm7pt_efficientnet_b0_final_results.json

Test Accuracy:
0.658228

Test Precision:
0.403409

Test Recall:
0.702970

Test F1:
0.512635

Test ROC-AUC:
0.742844
✅ FINAL TEST RESULTS SAFELY RECORDED

In [27]:
# DERM7PT EFFICIENTNET-B0 FINAL ARTIFACT VERIFICATION
# Purpose: Verify all EfficientNet-B0 training and evaluation
#          artifacts before creating the permanent backup.

import os


EFFICIENTNET_FINAL_ARTIFACTS = {
    "Best model": EFFICIENTNET_BEST_PATH,
    "Training history": EFFICIENTNET_HISTORY_PATH,
    "Baseline results": EFFICIENTNET_RESULTS_PATH,
    "Final results": EFFICIENTNET_FINAL_RESULTS_PATH
}


print("=" * 60)
print("DERM7PT EFFICIENTNET-B0 FINAL ARTIFACT VERIFICATION")
print("=" * 60)


all_verified = True


for name, path in EFFICIENTNET_FINAL_ARTIFACTS.items():

    exists = os.path.exists(path)

    print(f"\n{name}:")
    print(path)

    print("Exists:")
    print(exists)

    if exists:

        size_mb = (
            os.path.getsize(path)
            / (1024 ** 2)
        )

        print(
            f"Size: {size_mb:.2f} MB"
        )

    else:

        all_verified = False



if all_verified:

    print(
        "✅ ALL EFFICIENTNET-B0 FINAL ARTIFACTS VERIFIED"
    )

else:

    print(
        "❌ SOME EFFICIENTNET-B0 ARTIFACTS ARE MISSING"
    )

============================================================
DERM7PT EFFICIENTNET-B0 FINAL ARTIFACT VERIFICATION
============================================================

Best model:
/kaggle/working/derm7pt_efficientnet_b0_best.pth
Exists:
True
Size: 15.59 MB

Training history:
/kaggle/working/derm7pt_efficientnet_b0_training_history.pt
Exists:
True
Size: 0.00 MB

Baseline results:
/kaggle/working/derm7pt_efficientnet_b0_baseline_results.json
Exists:
True
Size: 0.00 MB

Final results:
/kaggle/working/derm7pt_efficientnet_b0_final_results.json
Exists:
True
Size: 0.00 MB
✅ ALL EFFICIENTNET-B0 FINAL ARTIFACTS VERIFIED

In [3]:
# --- Restore EfficientNet-B0 artifact paths ---

EFFICIENTNET_BEST_PATH = "/kaggle/working/derm7pt_efficientnet_b0_best.pth"
EFFICIENTNET_HISTORY_PATH = "/kaggle/working/derm7pt_efficientnet_b0_training_history.pt"
EFFICIENTNET_RESULTS_PATH = "/kaggle/working/derm7pt_efficientnet_b0_baseline_results.json"
EFFICIENTNET_FINAL_RESULTS_PATH = "/kaggle/working/derm7pt_efficientnet_b0_final_results.json"

EFFICIENTNET_ARTIFACT_PATHS = [
    EFFICIENTNET_BEST_PATH,
    EFFICIENTNET_HISTORY_PATH,
    EFFICIENTNET_RESULTS_PATH,
    EFFICIENTNET_FINAL_RESULTS_PATH
]

import os

print("Checking EfficientNet-B0 artifacts...")

for path in EFFICIENTNET_ARTIFACT_PATHS:
    print(os.path.basename(path), "->", os.path.exists(path))

print("\nArtifact paths restored.")

Checking EfficientNet-B0 artifacts...
derm7pt_efficientnet_b0_best.pth -> False
derm7pt_efficientnet_b0_training_history.pt -> False
derm7pt_efficientnet_b0_baseline_results.json -> False
derm7pt_efficientnet_b0_final_results.json -> False

Artifact paths restored.

In [2]:
# DERM7PT DATASET PATH DISCOVERY
# Purpose: Locate the exact Derm7pt dataset directory and inspect its top-level contents.

import os

BASE_PATH = "/kaggle/input/datasets/akansha1009"

print("DERM7PT DATASET PATH DISCOVERY")

print("\nBase path:")
print(BASE_PATH)

print("\nBase path exists:", os.path.exists(BASE_PATH))

if os.path.exists(BASE_PATH):
    print("\nContents:\n")

    for item in sorted(os.listdir(BASE_PATH)):
        full_path = os.path.join(BASE_PATH, item)

        if os.path.isdir(full_path):
            print(f"📁 {item}/")
        else:
            size_mb = os.path.getsize(full_path) / (1024 ** 2)
            print(f"📄 {item} ({size_mb:.2f} MB)")

print("✅ DATASET PATH DISCOVERY COMPLETED")

DERM7PT DATASET PATH DISCOVERY

Base path:
/kaggle/input/datasets/akansha1009

Base path exists: True

Contents:

📁 derm7pt-frozen-dataset/
✅ DATASET PATH DISCOVERY COMPLETED

In [3]:
# DERM7PT COMPLETE DATASET VERIFICATION
# Purpose: Verify the images, metadata files, and frozen research CSV before modeling.

import os
import pandas as pd

DATASET_PATH = "/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset"

print("DERM7PT COMPLETE DATASET VERIFICATION")

print("\nDataset path:")
print(DATASET_PATH)

print("\nDataset exists:", os.path.exists(DATASET_PATH))

print("\nTop-level contents:")

for item in sorted(os.listdir(DATASET_PATH)):
    full_path = os.path.join(DATASET_PATH, item)
    print("📁" if os.path.isdir(full_path) else "📄", item)


# Locate image directory

image_root = os.path.join(DATASET_PATH, "images")

if not os.path.exists(image_root):
    raise FileNotFoundError("images/ directory was not found.")

image_files = []

for root, _, files in os.walk(image_root):
    for filename in files:
        if filename.lower().endswith((".jpg", ".jpeg", ".png")):
            image_files.append(os.path.join(root, filename))

print("\nTotal image files:", len(image_files))

# Locate metadata directory

meta_root = os.path.join(DATASET_PATH, "meta")

print("\nMetadata directory exists:", os.path.exists(meta_root))

if os.path.exists(meta_root):
    print("\nMetadata files:")

    for filename in sorted(os.listdir(meta_root)):
        print("•", filename)

# Locate frozen research CSV

frozen_csv = os.path.join(
    DATASET_PATH,
    "Derm7pt_split_metadata.csv"
)

print("\nFrozen research CSV:")
print(frozen_csv)

print("Frozen CSV exists:", os.path.exists(frozen_csv))

if os.path.exists(frozen_csv):
    frozen_df = pd.read_csv(frozen_csv)

    print("\nFrozen metadata records:", len(frozen_df))

    print("\nFrozen metadata columns:")
    print(list(frozen_df.columns))

    print("\nSplit distribution:")
    print(frozen_df["split"].value_counts().sort_index())

    print("\nBinary label distribution:")
    print(frozen_df["binary_label"].value_counts().sort_index())


if len(image_files) == 2013 and os.path.exists(frozen_csv):
    print("✅ DERM7PT DATASET CONTENTS VERIFIED")
else:
    print("⚠️ DATASET REQUIRES FURTHER INSPECTION")

DERM7PT COMPLETE DATASET VERIFICATION

Dataset path:
/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset

Dataset exists: True

Top-level contents:
📁 Derm7pt_Kaggle_Ready
📄 Derm7pt_split_metadata.csv

FileNotFoundError: images/ directory was not found.

In [4]:
# DERM7PT KAGGLE STRUCTURE DIAGNOSTIC
# Purpose: Inspect the complete mounted directory structure and locate images, metadata, and the frozen CSV.

import os

BASE_PATH = "/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset"

print("DERM7PT KAGGLE STRUCTURE DIAGNOSTIC")

print("\nMounted dataset:")
print(BASE_PATH)

print("\nDirectory tree:\n")

for root, dirs, files in os.walk(BASE_PATH):
    relative = os.path.relpath(root, BASE_PATH)

    if relative == ".":
        level = 0
    else:
        level = relative.count(os.sep) + 1

    indent = "    " * level

    print(f"{indent}📁 {os.path.basename(root)}/")

    for filename in sorted(files)[:20]:
        print(f"{indent}    📄 {filename}")

print("SEARCHING FOR IMPORTANT DATA COMPONENTS")

image_count = 0
csv_files = []
zip_files = []

for root, dirs, files in os.walk(BASE_PATH):

    for filename in files:

        lower = filename.lower()
        full_path = os.path.join(root, filename)

        if lower.endswith((".jpg", ".jpeg", ".png")):
            image_count += 1

        if lower.endswith(".csv"):
            csv_files.append(full_path)

        if lower.endswith(".zip"):
            zip_files.append(full_path)

print("\nTotal image files found:", image_count)

print("\nCSV files found:")
for path in csv_files:
    print("•", path)

print("\nZIP files found:")
for path in zip_files:
    print("•", path)

print("✅ STRUCTURE DIAGNOSTIC COMPLETED")

DERM7PT KAGGLE STRUCTURE DIAGNOSTIC

Mounted dataset:
/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset

Directory tree:

📁 derm7pt-frozen-dataset/
    📄 Derm7pt_split_metadata.csv
    📁 Derm7pt_Kaggle_Ready/
        📄 README.txt
        📄 clinic.html
        📄 derm.html
        📁 meta/
            📄 meta.csv
            📄 test_indexes.csv
            📄 train_indexes.csv
            📄 valid_indexes.csv
        📁 images/
            📁 Gdl/
                📄 Gdl011.jpg
                📄 Gdl012.jpg
                📄 Gdl013.jpg
                📄 Gdl014.jpg
                📄 Gdl019.jpg
                📄 Gdl021.jpg
                📄 Gdl022.jpg
                📄 Gdl023.jpg
                📄 Gdl024.jpg
                📄 Gdl025.jpg
                📄 Gdl033.jpg
                📄 Gdl034.jpg
                📄 Gdl035.jpg
                📄 Gdl037.jpg
                📄 Gdl088.jpg
                📄 Gdl089.jpg
                📄 Gdl099.jpg
                📄 Gdl100.jpg
            📁 NFL/
                📄 NFL013.JPG
                📄 NFL023.JPG
                📄 NFL028.JPG
                📄 NFL051.JPG
                📄 Nfl003.jpg
                📄 Nfl004.jpg
                📄 Nfl005.jpg
                📄 Nfl006.jpg
                📄 Nfl007.jpg
                📄 Nfl008.jpg
                📄 Nfl009.jpg
                📄 Nfl010.jpg
                📄 Nfl011.jpg
                📄 Nfl012.jpg
                📄 Nfl014.jpg
                📄 Nfl015.jpg
                📄 Nfl016.jpg
                📄 Nfl017.jpg
                📄 Nfl018.jpg
                📄 Nfl019.jpg
            📁 NCL/
                📄 NCL070.JPG
                📄 NCL077.JPG
                📄 Ncl003.jpg
                📄 Ncl004.jpg
                📄 Ncl005.jpg
                📄 Ncl006.jpg
                📄 Ncl007.jpg
                📄 Ncl008.jpg
                📄 Ncl009.jpg
                📄 Ncl010.jpg
                📄 Ncl011.jpg
                📄 Ncl012.jpg
                📄 Ncl013.jpg
                📄 Ncl014.jpg
                📄 Ncl019.jpg
                📄 Ncl020.jpg
                📄 Ncl021.jpg
                📄 Ncl022.jpg
                📄 Ncl026.jpg
                📄 Ncl027.jpg
            📁 NAL/
                📄 NAL085.JPG
                📄 Nal002.jpg
                📄 Nal003.jpg
                📄 Nal005.jpg
                📄 Nal007.jpg
                📄 Nal008.jpg
                📄 Nal009.jpg
                📄 Nal017.jpg
                📄 Nal018.jpg
                📄 Nal019.jpg
                📄 Nal020.jpg
                📄 Nal021.jpg
                📄 Nal022.jpg
                📄 Nal025.jpg
                📄 Nal026.jpg
                📄 Nal033.jpg
                📄 Nal034.jpg
                📄 Nal035.jpg
                📄 Nal036.jpg
                📄 Nal037.jpg
            📁 Fil/
                📄 Fil003.jpg
                📄 Fil004.jpg
                📄 Fil005.jpg
                📄 Fil006.jpg
                📄 Fil007.jpg
                📄 Fil008.jpg
                📄 Fil009.jpg
                📄 Fil010.jpg
                📄 Fil031.jpg
                📄 Fil032.jpg
                📄 Fil039.jpg
                📄 Fil040.jpg
                📄 Fil051.jpg
                📄 Fil052.jpg
                📄 Fil061.jpg
                📄 Fil062.jpg
                📄 Fil063.jpg
                📄 Fil064.jpg
                📄 Fil069.jpg
                📄 Fil070.jpg
            📁 Ggl/
                📄 Ggl001.jpg
                📄 Ggl002.jpg
                📄 Ggl003.jpg
                📄 Ggl004.jpg
                📄 Ggl005.jpg
                📄 Ggl006.jpg
                📄 Ggl007.jpg
                📄 Ggl008.jpg
                📄 Ggl009.jpg
                📄 Ggl010.jpg
                📄 Ggl011.jpg
                📄 Ggl012.jpg
                📄 Ggl013.jpg
                📄 Ggl014.jpg
                📄 Ggl015.jpg
                📄 Ggl016.jpg
                📄 Ggl017.jpg
                📄 Ggl018.jpg
                📄 Ggl019.jpg
                📄 Ggl020.jpg
            📁 NML/
                📄 NML001.JPG
                📄 NML005.JPG
                📄 NML009.JPG
                📄 NML011.JPG
                📄 NML015.JPG
                📄 NML017.jpg
                📄 NML032.JPG
                📄 NML091.jpg
                📄 NML092.jpg
                📄 NML097.JPG
                📄 Nml002.jpg
                📄 Nml003.jpg
                📄 Nml004.jpg
                📄 Nml006.jpg
                📄 Nml007.jpg
                📄 Nml008.jpg
                📄 Nml010.jpg
                📄 Nml012.jpg
                📄 Nml013.jpg
                📄 Nml014.jpg
            📁 Gal/
                📄 Gal005.jpg
                📄 Gal006.jpg
                📄 Gal007.jpg
                📄 Gal008.jpg
                📄 Gal009.jpg
                📄 Gal010.jpg
                📄 Gal015.jpg
                📄 Gal016.jpg
                📄 Gal024.jpg
                📄 Gal025.jpg
                📄 Gal032.jpg
                📄 Gal033.jpg
                📄 Gal038.jpg
                📄 Gal039.jpg
                📄 Gal042.jpg
                📄 Gal043.jpg
                📄 Gal044.jpg
                📄 Gal045.jpg
                📄 Gal046.jpg
                📄 Gal047.jpg
            📁 NBL/
                📄 NBL021.JPG
                📄 NBL041.JPG
                📄 NBL043.JPG
                📄 NBL047.JPG
                📄 NBL049.JPG
                📄 Nbl001.jpg
                📄 Nbl002.jpg
                📄 Nbl003.jpg
                📄 Nbl004.jpg
                📄 Nbl005.jpg
                📄 Nbl006.jpg
                📄 Nbl007.jpg
                📄 Nbl008.jpg
                📄 Nbl009.jpg
                📄 Nbl010.jpg
                📄 Nbl012.jpg
                📄 Nbl013.jpg
                📄 Nbl014.jpg
                📄 Nbl015.jpg
                📄 Nbl017.jpg
            📁 NHL/
                📄 NHL016.JPG
                📄 Nhl008.jpg
                📄 Nhl009.jpg
                📄 Nhl010.jpg
                📄 Nhl011.jpg
                📄 Nhl012.jpg
                📄 Nhl013.jpg
                📄 Nhl014.jpg
                📄 Nhl015.jpg
                📄 Nhl017.jpg
            📁 FEL/
                📄 FEL001.JPG
                📄 Fel002.jpg
                📄 Fel015.jpg
                📄 Fel016.jpg
                📄 Fel017.jpg
                📄 Fel018.jpg
                📄 Fel023.jpg
                📄 Fel024.jpg
                📄 Fel029.jpg
                📄 Fel030.jpg
                📄 Fel033.jpg
                📄 Fel034.jpg
                📄 Fel037.jpg
                📄 Fel038.jpg
                📄 Fel051.jpg
                📄 Fel052.jpg
                📄 Fel063.jpg
                📄 Fel064.jpg
                📄 Fel067.jpg
                📄 Fel068.jpg
            📁 Fll/
                📄 Fll018.jpg
                📄 Fll019.jpg
                📄 Fll020.jpg
                📄 Fll021.jpg
                📄 Fll022.jpg
                📄 Fll023.jpg
                📄 Fll026.jpg
                📄 Fll027.jpg
                📄 Fll034.jpg
                📄 Fll035.jpg
                📄 Fll036.jpg
                📄 Fll037.jpg
                📄 Fll038.jpg
                📄 Fll039.jpg
                📄 Fll040.jpg
                📄 Fll041.jpg
                📄 Fll042.jpg
                📄 Fll043.jpg
                📄 Fll044.jpg
                📄 Fll045.jpg
            📁 FDL/
                📄 FDL016.JPG
                📄 FDL022.JPG
                📄 FDL026.JPG
                📄 FDL035.JPG
                📄 FDL036.JPG
                📄 FDL052.JPG
                📄 FDL055.JPG
                📄 FDL068.JPG
                📄 Fdl001.jpg
                📄 Fdl002.jpg
                📄 Fdl013.jpg
                📄 Fdl014.jpg
                📄 Fdl015.jpg
                📄 Fdl019.jpg
                📄 Fdl020.jpg
                📄 Fdl021.jpg
                📄 Fdl025.jpg
                📄 Fdl027.jpg
                📄 Fdl028.jpg
                📄 Fdl029.jpg
            📁 A2l/
                📄 Abl100.jpg
                📄 Abl101.jpg
                📄 Abl107.jpg
                📄 Abl108.jpg
                📄 Abl111.jpg
                📄 Abl112.jpg
                📄 Abl115.jpg
                📄 Abl116.jpg
                📄 Abl117.jpg
                📄 Abl118.jpg
                📄 Abl120.jpg
                📄 Abl121.jpg
                📄 Abl122.jpg
                📄 Abl123.jpg
                📄 Abl126.jpg
                📄 Abl127.jpg
                📄 Abl128.jpg
                📄 Abl129.jpg
                📄 Abl134.jpg
                📄 Abl135.jpg
            📁 FCL/
                📄 FCL011.JPG
                📄 FCL017.JPG
                📄 FCL018.JPG
                📄 FCL021.JPG
                📄 FCL023.JPG
                📄 FCL025.JPG
                📄 FCL031.JPG
                📄 FCL037.JPG
                📄 FCL047.JPG
                📄 FCL052.JPG
                📄 FCL053.JPG
                📄 FCL054.JPG
                📄 FCL056.JPG
                📄 FCL058.JPG
                📄 FCL066.JPG
                📄 FCL067.JPG
                📄 FCL069.JPG
                📄 FCL073.JPG
                📄 FCL074.JPG
                📄 FCL075.JPG
            📁 FCl/
                📄 Fcl068.jpg
            📁 A1l/
                📄 Aal001.jpg
                📄 Aal001bis.jpg
                📄 Aal002.jpg
                📄 Aal002bis.jpg
                📄 Aal003.jpg
                📄 Aal004.jpg
                📄 Aal005.jpg
                📄 Aal006.jpg
                📄 Aal007.jpg
                📄 Aal008.jpg
                📄 Aal009.jpg
                📄 Aal010.jpg
                📄 Aal011.jpg
                📄 Aal012.jpg
                📄 Aal013.jpg
                📄 Aal014.jpg
                📄 Aal017.jpg
                📄 Aal018.jpg
                📄 Aal019.jpg
                📄 Aal020.jpg
            📁 FBL/
                📄 FBL003.JPG
                📄 FBL009.JPG
                📄 FBL012.JPG
                📄 FBL020.JPG
                📄 FBL026.JPG
                📄 FBL031.JPG
                📄 FBL032.JPG
                📄 FBL042.JPG
                📄 FBL043.JPG
                📄 FBL046.JPG
                📄 FBL047.JPG
                📄 FBL058.JPG
                📄 FBL061.JPG
                📄 FBL062.JPG
                📄 FBL066.JPG
                📄 FBL071.JPG
                📄 Fbl001.jpg
                📄 Fbl002.jpg
                📄 Fbl004.jpg
                📄 Fbl005.jpg
            📁 Fml/
                📄 Fml009.jpg
                📄 Fml010.jpg
                📄 Fml019.jpg
                📄 Fml020.jpg
                📄 Fml025.jpg
                📄 Fml026.jpg
            📁 Fgl/
                📄 Fgl001.jpg
                📄 Fgl002.jpg
                📄 Fgl003.jpg
                📄 Fgl005.jpg
                📄 Fgl006.jpg
                📄 Fgl007.jpg
                📄 Fgl008.jpg
                📄 Fgl009.jpg
                📄 Fgl010.jpg
                📄 Fgl011.jpg
                📄 Fgl012.jpg
                📄 Fgl013.jpg
                📄 Fgl014.jpg
                📄 Fgl017.jpg
                📄 Fgl018.jpg
                📄 Fgl019.jpg
                📄 Fgl020.jpg
                📄 Fgl022.jpg
                📄 Fgl023.jpg
                📄 Fgl025.jpg
            📁 NEL/
                📄 NEL009.JPG
                📄 NEL011.JPG
                📄 NEL022.JPG
                📄 NEL025.JPG
                📄 NEL027.JPG
                📄 NEL034.JPG
                📄 NEL036.JPG
                📄 NEL055.JPG
                📄 NEL088.JPG
                📄 NEL090.JPG
                📄 NEL093.JPG
                📄 NEL096.JPG
                📄 NEL099.JPG
                📄 Nel005.jpg
                📄 Nel006.jpg
                📄 Nel008.jpg
                📄 Nel010.jpg
                📄 Nel012.jpg
                📄 Nel013.jpg
                📄 Nel021.jpg
            📁 New/
                📄 newl001.jpg
                📄 newl002.jpg
                📄 newl005.jpg
                📄 newl006.jpg
                📄 newl007.jpg
                📄 newl008.jpg
                📄 newl009.jpg
                📄 newl010.jpg
                📄 newl011.jpg
                📄 newl012.jpg
                📄 newl013.jpg
                📄 newl014.jpg
                📄 newl015.jpg
                📄 newl016.jpg
                📄 newl017.jpg
                📄 newl018.jpg
                📄 newl019.jpg
                📄 newl020.jpg
                📄 newl021.jpg
                📄 newl022.jpg
            📁 Gcl/
                📄 Gcl001.jpg
                📄 Gcl003.jpg
                📄 Gcl038.jpg
                📄 Gcl039.jpg
                📄 Gcl051.jpg
                📄 Gcl052.jpg
                📄 Gcl057.jpg
                📄 Gcl058.jpg
                📄 Gcl072.jpg
                📄 Gcl073.jpg
                📄 Gcl093.jpg
                📄 Gcl094.jpg
            📁 Gbl/
                📄 Gbl006.jpg
                📄 Gbl009.jpg
                📄 Gbl013.jpg
                📄 Gbl014.jpg
            📁 A3l/
                📄 Acl200.jpg
                📄 Acl201.jpg
                📄 Acl202.jpg
                📄 Acl203.jpg
                📄 Acl204.jpg
                📄 Acl205.jpg
                📄 Acl206.jpg
                📄 Acl207.jpg
                📄 Acl208.jpg
                📄 Acl209.jpg
                📄 Acl210.jpg
                📄 Acl211.jpg
                📄 Acl214.jpg
                📄 Acl215.jpg
                📄 Acl216.jpg
                📄 Acl217.jpg
                📄 Acl218.jpg
                📄 Acl219.jpg
                📄 Acl220.jpg
                📄 Acl221.jpg
            📁 Fhl/
                📄 Fhl002.jpg
                📄 Fhl003.jpg
                📄 Fhl004.jpg
                📄 Fhl005.jpg
                📄 Fhl006.jpg
                📄 Fhl007.jpg
                📄 Fhl008.jpg
                📄 Fhl009.jpg
                📄 Fhl010.jpg
                📄 Fhl012.jpg
                📄 Fhl013.jpg
                📄 Fhl014.jpg
                📄 Fhl015.jpg
                📄 Fhl016.jpg
                📄 Fhl018.jpg
                📄 Fhl021.jpg
                📄 Fhl022.jpg
                📄 Fhl027.jpg
                📄 Fhl028.jpg
                📄 Fhl029.jpg
            📁 FFL/
                📄 FFL002.JPG
                📄 FFL004.JPG
                📄 FFL006.JPG
                📄 FFL008.JPG
                📄 FFL020.JPG
                📄 FFL032.JPG
                📄 FFL052.JPG
                📄 FFL068.JPG
                📄 Ffl001.jpg
                📄 Ffl003.jpg
                📄 Ffl005.jpg
                📄 Ffl007.jpg
                📄 Ffl009.jpg
                📄 Ffl010.jpg
                📄 Ffl013.jpg
                📄 Ffl014.jpg
                📄 Ffl015.jpg
                📄 Ffl016.jpg
                📄 Ffl019.jpg
                📄 Ffl025.jpg
            📁 Ael/
                📄 Ael400.jpg
                📄 Ael401.jpg
                📄 Ael404.jpg
                📄 Ael405.jpg
                📄 Ael406.jpg
                📄 Ael407.jpg
                📄 Ael408.jpg
                📄 Ael409.jpg
                📄 Ael412.jpg
                📄 Ael413.jpg
                📄 Ael414.jpg
                📄 Ael415.jpg
                📄 Ael418.jpg
                📄 Ael419.jpg
                📄 Ael420.jpg
                📄 Ael421.jpg
                📄 Ael424.jpg
                📄 Ael425.jpg
                📄 Ael426.jpg
                📄 Ael427.jpg
            📁 NGL/
                📄 NGL003.JPG
                📄 NGL005.JPG
                📄 NGL009.JPG
                📄 NGL010.JPG
                📄 NGL014.JPG
                📄 NGL025.JPG
                📄 NGL026.JPG
                📄 NGL046.JPG
                📄 NGL048.JPG
                📄 Ngl001.jpg
                📄 Ngl002.jpg
                📄 Ngl004.jpg
                📄 Ngl006.jpg
                📄 Ngl007.jpg
                📄 Ngl008.jpg
                📄 Ngl012.jpg
                📄 Ngl013.jpg
                📄 Ngl015.jpg
                📄 Ngl016.jpg
                📄 Ngl017.jpg
            📁 NIL/
                📄 NIL055.JPG
                📄 NIL063.JPG
                📄 NIL077.JPG
                📄 NIL101.JPG
                📄 Nil001.jpg
                📄 Nil002.jpg
                📄 Nil003.jpg
                📄 Nil004.jpg
                📄 Nil005.jpg
                📄 Nil006.jpg
                📄 Nil007.jpg
                📄 Nil008.jpg
                📄 Nil009.jpg
                📄 Nil010.jpg
                📄 Nil020.jpg
                📄 Nil021.jpg
                📄 Nil022.jpg
                📄 Nil023.jpg
                📄 Nil024.jpg
                📄 Nil025.jpg
            📁 Gzl/
                📄 gzl01.jpg
                📄 gzl02.jpg
                📄 gzl03.jpg
                📄 gzl04.jpg
                📄 gzl05.jpg
                📄 gzl06.jpg
                📄 gzl07.jpg
                📄 gzl08.jpg
                📄 gzl09.jpg
                📄 gzl10.jpg
                📄 gzl11.jpg
                📄 gzl12.jpg
                📄 gzl13.jpg
                📄 gzl14.jpg
                📄 gzl15.jpg
                📄 gzl16.jpg
                📄 gzl17.jpg
                📄 gzl18.jpg
                📄 gzl19.jpg
                📄 gzl20.jpg
            📁 NLL/
                📄 NLL003.JPG
                📄 NLL034.JPG
                📄 NLL045.JPG
                📄 NLL047.JPG
                📄 NLL052.JPG
                📄 NLL065.JPG
                📄 NLL067.JPG
                📄 Nll001.jpg
                📄 Nll002.jpg
                📄 Nll004.jpg
                📄 Nll013.jpg
                📄 Nll015.jpg
                📄 Nll016.jpg
                📄 Nll017.jpg
                📄 Nll018.jpg
                📄 Nll019.jpg
                📄 Nll020.jpg
                📄 Nll021.jpg
                📄 Nll023.jpg
                📄 Nll024.jpg
            📁 Adl/
                📄 Adl300.jpg
                📄 Adl301.jpg
                📄 Adl304.jpg
                📄 Adl305.jpg
                📄 Adl310.jpg
                📄 Adl311.jpg
                📄 Adl312.jpg
                📄 Adl313.jpg
                📄 Adl318.jpg
                📄 Adl319.jpg
                📄 Adl320.jpg
                📄 Adl321.jpg
                📄 Adl324.jpg
                📄 Adl325.jpg
                📄 Adl328.jpg
                📄 Adl329.jpg
                📄 Adl330.jpg
                📄 Adl331.jpg
                📄 Adl332.jpg
                📄 Adl333.jpg
            📁 NDL/
                📄 NDL034.JPG
                📄 NDL049.JPG
                📄 NDL053.JPG
                📄 NDL062.JPG
                📄 NDL063.JPG
                📄 NDL064.JPG
                📄 Ndl005.jpg
                📄 Ndl006.jpg
                📄 Ndl009.jpg
                📄 Ndl010.jpg
                📄 Ndl011.jpg
                📄 Ndl012.jpg
                📄 Ndl017.jpg
                📄 Ndl018.jpg
                📄 Ndl020.jpg
                📄 Ndl021.jpg
                📄 Ndl022.jpg
                📄 Ndl023.jpg
                📄 Ndl024.jpg
                📄 Ndl025.jpg
            📁 FAL/
                📄 FAL006.JPG
                📄 FAL022.JPG
                📄 FAL036.JPG
                📄 FAL038.JPG
                📄 FAL042.JPG
                📄 FAL044.JPG
                📄 FAL054.JPG
                📄 FAL066.JPG
                📄 FAL070.JPG
                📄 FAL094.JPG
                📄 Fal005.jpg
                📄 Fal010.jpg
                📄 Fal012.jpg
                📄 Fal019.jpg
                📄 Fal020.jpg
                📄 Fal021.jpg
                📄 Fal023.jpg
                📄 Fal024.jpg
                📄 Fal035.jpg
                📄 Fal037.jpg
SEARCHING FOR IMPORTANT DATA COMPONENTS

Total image files found: 2013

CSV files found:
• /kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_split_metadata.csv
• /kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_Kaggle_Ready/meta/train_indexes.csv
• /kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_Kaggle_Ready/meta/valid_indexes.csv
• /kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_Kaggle_Ready/meta/meta.csv
• /kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_Kaggle_Ready/meta/test_indexes.csv


In [5]:
# DERM7PT KAGGLE FROZEN METADATA VALIDATION
# Purpose: Verify that every frozen clinical and dermoscopic
#          image reference resolves correctly inside Kaggle.

import os
import pandas as pd


DATASET_ROOT = (
    "/kaggle/input/datasets/akansha1009/"
    "derm7pt-frozen-dataset"
)

FROZEN_CSV = os.path.join(
    DATASET_ROOT,
    "Derm7pt_split_metadata.csv"
)

IMAGE_ROOT = os.path.join(
    DATASET_ROOT,
    "Derm7pt_Kaggle_Ready",
    "images"
)


print("DERM7PT KAGGLE FROZEN METADATA VALIDATION")


metadata = pd.read_csv(
    FROZEN_CSV
)


print("\nFrozen metadata records:")
print(len(metadata))


print("\nColumns:")
print(metadata.columns.tolist())


print("\nSplit distribution:")
print(
    metadata["split"]
    .value_counts()
    .sort_index()
)


print("\nBinary label distribution:")
print(
    metadata["binary_label"]
    .value_counts()
    .sort_index()
)


clinic_missing = []
derm_missing = []


for _, row in metadata.iterrows():

    clinic_path = str(
        row["clinic_path"]
    )

    derm_path = str(
        row["derm_path"]
    )


    clinic_full = os.path.join(
        IMAGE_ROOT,
        os.path.basename(clinic_path)
    )


    derm_full = os.path.join(
        IMAGE_ROOT,
        os.path.basename(derm_path)
    )


    if not os.path.exists(
        clinic_full
    ):

        clinic_missing.append(
            clinic_path
        )


    if not os.path.exists(
        derm_full
    ):

        derm_missing.append(
            derm_path
        )


print("\nClinical image references:")
print(len(metadata))

print("Missing clinical images:")
print(len(clinic_missing))


print("\nDermoscopic image references:")
print(len(metadata))

print("Missing dermoscopic images:")
print(len(derm_missing))




if (
    len(clinic_missing) == 0
    and len(derm_missing) == 0
):

    print(
        "✅ ALL FROZEN IMAGE REFERENCES RESOLVE IN KAGGLE"
    )

else:

    print(
        "❌ SOME IMAGE REFERENCES DO NOT RESOLVE"
    )

DERM7PT KAGGLE FROZEN METADATA VALIDATION

Frozen metadata records:
1011

Columns:
['case_num', 'diagnosis', 'binary_label', 'label', 'clinic', 'derm', 'split', 'clinic_path', 'derm_path']

Split distribution:
split
test          395
train         413
validation    203
Name: count, dtype: int64

Binary label distribution:
binary_label
Melanoma        252
Non-Melanoma    759
Name: count, dtype: int64

Clinical image references:
1011
Missing clinical images:
1011

Dermoscopic image references:
1011
Missing dermoscopic images:
1011
❌ SOME IMAGE REFERENCES DO NOT RESOLVE

In [6]:
# DERM7PT KAGGLE IMAGE PATH VALIDATION - FINAL CORRECTION
# Purpose: Verify frozen clinical and dermoscopic paths against
#          the exact directory structure of the Kaggle dataset.

import os
import pandas as pd


DATASET_ROOT = (
    "/kaggle/input/datasets/akansha1009/"
    "derm7pt-frozen-dataset"
)

FROZEN_CSV = os.path.join(
    DATASET_ROOT,
    "Derm7pt_split_metadata.csv"
)

IMAGE_ROOT = os.path.join(
    DATASET_ROOT,
    "Derm7pt_Kaggle_Ready",
    "images"
)


metadata = pd.read_csv(
    FROZEN_CSV
)


clinic_missing = []
derm_missing = []


for _, row in metadata.iterrows():

    clinic_path = str(
        row["clinic_path"]
    ).replace("\\", "/")

    derm_path = str(
        row["derm_path"]
    ).replace("\\", "/")


    if clinic_path.startswith("images/"):
        clinic_path = clinic_path[len("images/"):]

    if derm_path.startswith("images/"):
        derm_path = derm_path[len("images/"):]


    clinic_full_path = os.path.join(
        IMAGE_ROOT,
        clinic_path
    )

    derm_full_path = os.path.join(
        IMAGE_ROOT,
        derm_path
    )


    if not os.path.exists(
        clinic_full_path
    ):

        clinic_missing.append(
            {
                "case_num": row["case_num"],
                "path": clinic_path
            }
        )


    if not os.path.exists(
        derm_full_path
    ):

        derm_missing.append(
            {
                "case_num": row["case_num"],
                "path": derm_path
            }
        )


print("DERM7PT FINAL IMAGE PATH VALIDATION")

print("\nFrozen records:")
print(len(metadata))

print("\nClinical references:")
print(len(metadata))

print("Missing clinical images:")
print(len(clinic_missing))

print("\nDermoscopic references:")
print(len(metadata))

print("Missing dermoscopic images:")
print(len(derm_missing))



if (
    len(clinic_missing) == 0
    and len(derm_missing) == 0
):

    print(
        "✅ ALL 2,022 FROZEN IMAGE REFERENCES RESOLVE IN KAGGLE"
    )

else:

    print(
        "❌ SOME IMAGE REFERENCES STILL DO NOT RESOLVE"
    )

    if clinic_missing:
        print("\nFirst missing clinical reference:")
        print(clinic_missing[0])

    if derm_missing:
        print("\nFirst missing dermoscopic reference:")
        print(derm_missing[0])

DERM7PT FINAL IMAGE PATH VALIDATION

Frozen records:
1011

Clinical references:
1011
Missing clinical images:
1011

Dermoscopic references:
1011
Missing dermoscopic images:
1011
❌ SOME IMAGE REFERENCES STILL DO NOT RESOLVE

First missing clinical reference:
{'case_num': 1, 'path': '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL025.JPG'}

First missing dermoscopic reference:
{'case_num': 1, 'path': '/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel026.jpg'}

In [7]:
# DERM7PT KAGGLE IMAGE PATH VALIDATION - ABSOLUTE PATH FIX
# Purpose: Convert the frozen Google Drive image paths into
#          Kaggle-relative paths and verify every image reference.

import os
import pandas as pd


DATASET_ROOT = (
    "/kaggle/input/datasets/akansha1009/"
    "derm7pt-frozen-dataset"
)

FROZEN_CSV = os.path.join(
    DATASET_ROOT,
    "Derm7pt_split_metadata.csv"
)

IMAGE_ROOT = os.path.join(
    DATASET_ROOT,
    "Derm7pt_Kaggle_Ready",
    "images"
)


metadata = pd.read_csv(
    FROZEN_CSV
)


def convert_to_kaggle_path(original_path):

    path = str(
        original_path
    ).replace("\\", "/")

    marker = "/images/"

    if marker in path:

        relative_path = path.split(
            marker,
            1
        )[1]

    elif path.startswith("images/"):

        relative_path = path[len("images/"):]

    else:

        relative_path = path

    return os.path.join(
        IMAGE_ROOT,
        relative_path
    )


clinic_missing = []
derm_missing = []


for _, row in metadata.iterrows():

    clinic_full_path = convert_to_kaggle_path(
        row["clinic_path"]
    )

    derm_full_path = convert_to_kaggle_path(
        row["derm_path"]
    )


    if not os.path.exists(
        clinic_full_path
    ):

        clinic_missing.append(
            {
                "case_num": row["case_num"],
                "original_path": row["clinic_path"],
                "kaggle_path": clinic_full_path
            }
        )


    if not os.path.exists(
        derm_full_path
    ):

        derm_missing.append(
            {
                "case_num": row["case_num"],
                "original_path": row["derm_path"],
                "kaggle_path": derm_full_path
            }
        )


print("DERM7PT FINAL KAGGLE IMAGE PATH VALIDATION")

print("\nFrozen records:")
print(len(metadata))

print("\nClinical references:")
print(len(metadata))

print("Missing clinical images:")
print(len(clinic_missing))

print("\nDermoscopic references:")
print(len(metadata))

print("Missing dermoscopic images:")
print(len(derm_missing))


print("\nExample path conversion:")

example = metadata.iloc[0]

print("\nOriginal clinical path:")
print(example["clinic_path"])

print("\nConverted Kaggle clinical path:")
print(
    convert_to_kaggle_path(
        example["clinic_path"]
    )
)

print("\nOriginal dermoscopic path:")
print(example["derm_path"])

print("\nConverted Kaggle dermoscopic path:")
print(
    convert_to_kaggle_path(
        example["derm_path"]
    )
)



if (
    len(clinic_missing) == 0
    and len(derm_missing) == 0
):

    print(
        "✅ ALL 2,022 FROZEN IMAGE REFERENCES RESOLVE IN KAGGLE"
    )

else:

    print(
        "❌ SOME IMAGE REFERENCES STILL DO NOT RESOLVE"
    )

    if clinic_missing:
        print("\nFirst missing clinical reference:")
        print(clinic_missing[0])

    if derm_missing:
        print("\nFirst missing dermoscopic reference:")
        print(derm_missing[0])

DERM7PT FINAL KAGGLE IMAGE PATH VALIDATION

Frozen records:
1011

Clinical references:
1011
Missing clinical images:
0

Dermoscopic references:
1011
Missing dermoscopic images:
0

Example path conversion:

Original clinical path:
/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/NEL025.JPG

Converted Kaggle clinical path:
/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_Kaggle_Ready/images/NEL/NEL025.JPG

Original dermoscopic path:
/content/drive/MyDrive/Melanoma Skin Lesion Analysis Project/data/Derm7pt/raw/release_v0/images/NEL/Nel026.jpg

Converted Kaggle dermoscopic path:
/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_Kaggle_Ready/images/NEL/Nel026.jpg
✅ ALL 2,022 FROZEN IMAGE REFERENCES RESOLVE IN KAGGLE

In [8]:
# DERM7PT KAGGLE GPU VERIFICATION
# Purpose: Confirm CUDA availability and identify the GPUs
#          before starting classification experiments.

import torch

print("DERM7PT KAGGLE GPU VERIFICATION")

print("\nPyTorch version:")
print(torch.__version__)

print("\nCUDA available:")
print(torch.cuda.is_available())

print("\nGPU count:")
print(torch.cuda.device_count())


if torch.cuda.is_available():

    for i in range(torch.cuda.device_count()):

        print(
            f"GPU {i}: "
            f"{torch.cuda.get_device_name(i)}"
        )

        memory_gb = (
            torch.cuda.get_device_properties(i).total_memory
            / (1024 ** 3)
        )

        print(
            f"GPU {i} memory: "
            f"{memory_gb:.2f} GB"
        )

    DEVICE = torch.device("cuda")

    print("\nSelected device:")
    print(DEVICE)

    print(
        "\n✅ GPU READY FOR DERM7PT CLASSIFICATION"
    )

else:

    DEVICE = torch.device("cpu")

    print("\nSelected device:")
    print(DEVICE)

    print(
        "\n❌ GPU IS NOT AVAILABLE"
    )

DERM7PT KAGGLE GPU VERIFICATION

PyTorch version:
2.10.0+cu128

CUDA available:
True

GPU count:
2
GPU 0: Tesla T4
GPU 0 memory: 14.56 GB
GPU 1: Tesla T4
GPU 1 memory: 14.56 GB

Selected device:
cuda

✅ GPU READY FOR DERM7PT CLASSIFICATION

In [9]:
# DERM7PT FROZEN METADATA LOADING
# Purpose: Load the frozen research metadata that controls all
#          Derm7pt train, validation, and test experiments.

import os
import pandas as pd


DATASET_ROOT = (
    "/kaggle/input/datasets/akansha1009/"
    "derm7pt-frozen-dataset"
)

FROZEN_CSV = os.path.join(
    DATASET_ROOT,
    "Derm7pt_split_metadata.csv"
)

IMAGE_ROOT = os.path.join(
    DATASET_ROOT,
    "Derm7pt_Kaggle_Ready",
    "images"
)


df = pd.read_csv(
    FROZEN_CSV
)


print("DERM7PT FROZEN METADATA LOADING")

print("\nMetadata path:")
print(FROZEN_CSV)

print("\nRecords:")
print(len(df))

print("\nColumns:")
print(df.columns.tolist())

print("\nSplit distribution:")
print(
    df["split"]
    .value_counts()
    .sort_index()
)

print("\nBinary label distribution:")
print(
    df["binary_label"]
    .value_counts()
    .sort_index()
)

print("\nImage root:")
print(IMAGE_ROOT)

print("\nImage root exists:")
print(os.path.exists(IMAGE_ROOT))

print("✅ DERM7PT FROZEN METADATA LOADED")

DERM7PT FROZEN METADATA LOADING

Metadata path:
/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_split_metadata.csv

Records:
1011

Columns:
['case_num', 'diagnosis', 'binary_label', 'label', 'clinic', 'derm', 'split', 'clinic_path', 'derm_path']

Split distribution:
split
test          395
train         413
validation    203
Name: count, dtype: int64

Binary label distribution:
binary_label
Melanoma        252
Non-Melanoma    759
Name: count, dtype: int64

Image root:
/kaggle/input/datasets/akansha1009/derm7pt-frozen-dataset/Derm7pt_Kaggle_Ready/images

Image root exists:
True
✅ DERM7PT FROZEN METADATA LOADED

In [10]:
# DERM7PT PYTORCH CLASSIFICATION DATASET
# Purpose: Create a PyTorch Dataset using the frozen Derm7pt
#          metadata and verify image/label loading.

import os
import torch
from torch.utils.data import Dataset
from PIL import Image


class Derm7ptDataset(Dataset):

    def __init__(
        self,
        dataframe,
        image_root,
        transform=None
    ):

        self.dataframe = dataframe.reset_index(
            drop=True
        )

        self.image_root = image_root
        self.transform = transform


    def _get_image_path(self, path):

        path = str(path).replace("\\", "/")

        if "/images/" in path:
            relative_path = path.split(
                "/images/",
                1
            )[1]

        elif path.startswith("images/"):
            relative_path = path[len("images/"):]

        else:
            relative_path = path

        return os.path.join(
            self.image_root,
            relative_path
        )


    def __len__(self):

        return len(self.dataframe)


    def __getitem__(self, index):

        row = self.dataframe.iloc[index]

        image_path = self._get_image_path(
            row["derm_path"]
        )

        image = Image.open(
            image_path
        ).convert("RGB")

        label = 1 if row["binary_label"] == "Melanoma" else 0

        if self.transform is not None:
            image = self.transform(image)

        label = torch.tensor(
            label,
            dtype=torch.long
        )

        return image, label


train_df = df[
    df["split"] == "train"
].copy()

val_df = df[
    df["split"] == "validation"
].copy()

test_df = df[
    df["split"] == "test"
].copy()


train_dataset = Derm7ptDataset(
    train_df,
    IMAGE_ROOT
)

val_dataset = Derm7ptDataset(
    val_df,
    IMAGE_ROOT
)

test_dataset = Derm7ptDataset(
    test_df,
    IMAGE_ROOT
)


sample_image, sample_label = train_dataset[0]


print("DERM7PT PYTORCH DATASET")

print("\nTraining samples:")
print(len(train_dataset))

print("\nValidation samples:")
print(len(val_dataset))

print("\nTest samples:")
print(len(test_dataset))

print("\nSample image type:")
print(type(sample_image))

print("\nSample image size:")
print(sample_image.size)

print("\nSample label:")
print(sample_label.item())

print("\nSample label meaning:")
print(
    "Melanoma"
    if sample_label.item() == 1
    else "Non-Melanoma"
)

print("✅ DERM7PT PYTORCH DATASET READY")

DERM7PT PYTORCH DATASET

Training samples:
413

Validation samples:
203

Test samples:
395

Sample image type:
<class 'PIL.Image.Image'>

Sample image size:
(768, 512)

Sample label:
0

Sample label meaning:
Non-Melanoma
✅ DERM7PT PYTORCH DATASET READY

In [11]:
# DERM7PT IMAGE TRANSFORMS
# Purpose: Define training augmentation and deterministic
#          validation/test preprocessing for classification.

import torchvision.transforms as transforms


IMAGE_SIZE = 224


train_transform = transforms.Compose([
    transforms.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),
    transforms.RandomHorizontalFlip(
        p=0.5
    ),
    transforms.RandomVerticalFlip(
        p=0.2
    ),
    transforms.RandomRotation(
        degrees=15
    ),
    transforms.ColorJitter(
        brightness=0.15,
        contrast=0.15,
        saturation=0.10,
        hue=0.02
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


eval_transform = transforms.Compose([
    transforms.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


print("DERM7PT IMAGE TRANSFORMS")

print("\nImage size:")
print(
    f"{IMAGE_SIZE} × {IMAGE_SIZE}"
)

print("\nTraining:")
print("Resize")
print("Random horizontal flip")
print("Random vertical flip")
print("Random rotation")
print("Color jitter")
print("Normalization")

print("\nValidation/Test:")
print("Resize")
print("Normalization")

print("✅ DERM7PT IMAGE TRANSFORMS READY")

DERM7PT IMAGE TRANSFORMS

Image size:
224 × 224

Training:
Resize
Random horizontal flip
Random vertical flip
Random rotation
Color jitter
Normalization

Validation/Test:
Resize
Normalization
✅ DERM7PT IMAGE TRANSFORMS READY

In [12]:
# DERM7PT TRANSFORMED PYTORCH DATASETS
# Purpose: Attach the training and evaluation transforms to the
#          frozen Derm7pt train/validation/test datasets.

train_dataset = Derm7ptDataset(
    train_df,
    IMAGE_ROOT,
    transform=train_transform
)

val_dataset = Derm7ptDataset(
    val_df,
    IMAGE_ROOT,
    transform=eval_transform
)

test_dataset = Derm7ptDataset(
    test_df,
    IMAGE_ROOT,
    transform=eval_transform
)


train_sample, train_label = train_dataset[0]
val_sample, val_label = val_dataset[0]
test_sample, test_label = test_dataset[0]


print("DERM7PT TRANSFORMED PYTORCH DATASETS")

print("\nTraining samples:")
print(len(train_dataset))

print("\nValidation samples:")
print(len(val_dataset))

print("\nTest samples:")
print(len(test_dataset))

print("\nTraining sample tensor shape:")
print(train_sample.shape)

print("\nValidation sample tensor shape:")
print(val_sample.shape)

print("\nTest sample tensor shape:")
print(test_sample.shape)

print("\nTraining sample dtype:")
print(train_sample.dtype)

print("\nTraining label:")
print(train_label.item())

print("✅ TRANSFORMED DATASETS READY")

DERM7PT TRANSFORMED PYTORCH DATASETS

Training samples:
413

Validation samples:
203

Test samples:
395

Training sample tensor shape:
torch.Size([3, 224, 224])

Validation sample tensor shape:
torch.Size([3, 224, 224])

Test sample tensor shape:
torch.Size([3, 224, 224])

Training sample dtype:
torch.float32

Training label:
0
✅ TRANSFORMED DATASETS READY

In [13]:
# DERM7PT GPU-OPTIMIZED DATALOADERS
# Purpose: Create reproducible DataLoaders for the frozen
#          Derm7pt train, validation, and test splits.

from torch.utils.data import DataLoader


BATCH_SIZE = 32
NUM_WORKERS = 2


train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    drop_last=False
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    drop_last=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    drop_last=False
)


print("DERM7PT GPU-OPTIMIZED DATALOADERS")

print("\nBatch size:")
print(BATCH_SIZE)

print("\nNumber of workers:")
print(NUM_WORKERS)

print("\nPin memory:")
print(True)

print("\nTraining batches:")
print(len(train_loader))

print("\nValidation batches:")
print(len(val_loader))

print("\nTest batches:")
print(len(test_loader))

print("✅ DERM7PT DATALOADERS READY")

DERM7PT GPU-OPTIMIZED DATALOADERS

Batch size:
32

Number of workers:
2

Pin memory:
True

Training batches:
13

Validation batches:
7

Test batches:
13
✅ DERM7PT DATALOADERS READY

In [14]:
# DERM7PT GPU BATCH TRANSFER TEST
# Purpose: Verify that a real Derm7pt batch loads correctly and
#          transfers successfully to the CUDA device.

import time
import torch


print("DERM7PT GPU BATCH TRANSFER TEST")


start_time = time.time()


images, labels = next(
    iter(train_loader)
)


print("\nCPU image shape:")
print(tuple(images.shape))

print("\nCPU label shape:")
print(tuple(labels.shape))

print("\nCPU image dtype:")
print(images.dtype)

print("\nCPU label dtype:")
print(labels.dtype)


print("\nTransferring batch to GPU...")


images_gpu = images.to(
    DEVICE,
    non_blocking=True
)

labels_gpu = labels.to(
    DEVICE,
    non_blocking=True
)


if torch.cuda.is_available():
    torch.cuda.synchronize()


elapsed_time = time.time() - start_time


print("\nGPU image shape:")
print(tuple(images_gpu.shape))

print("\nGPU label shape:")
print(tuple(labels_gpu.shape))

print("\nImage device:")
print(images_gpu.device)

print("\nLabel device:")
print(labels_gpu.device)

print("\nTransfer and loading time:")
print(f"{elapsed_time:.3f} seconds")

print("\nGPU memory allocated:")
print(
    f"{torch.cuda.memory_allocated() / (1024 ** 3):.2f} GB"
)



if images_gpu.device.type == "cuda":
    print("✅ GPU BATCH TRANSFER TEST PASSED")
else:
    print("❌ GPU BATCH TRANSFER TEST FAILED")

DERM7PT GPU BATCH TRANSFER TEST

CPU image shape:
(32, 3, 224, 224)

CPU label shape:
(32,)

CPU image dtype:
torch.float32

CPU label dtype:
torch.int64

Transferring batch to GPU...

GPU image shape:
(32, 3, 224, 224)

GPU label shape:
(32,)

Image device:
cuda:0

Label device:
cuda:0

Transfer and loading time:
1.558 seconds

GPU memory allocated:
0.02 GB
✅ GPU BATCH TRANSFER TEST PASSED

In [15]:
# DERM7PT RESNET-18 BASELINE
# Purpose: Define the first Derm7pt binary classification model
#          and prepare its final layer for two classes.

import torch
import torch.nn as nn
from torchvision.models import resnet18


model = resnet18(
    weights=None
)

num_features = model.fc.in_features

model.fc = nn.Linear(
    num_features,
    2
)


model = model.to(
    DEVICE
)


print("DERM7PT RESNET-18 BASELINE")

print("\nModel:")
print("ResNet-18")

print("\nInput:")
print("(batch, 3, 224, 224)")

print("\nOutput:")
print("(batch, 2)")

print("\nParameters:")
print(
    f"{sum(p.numel() for p in model.parameters()):,}"
)

print("\nModel device:")
print(next(model.parameters()).device)

print("✅ RESNET-18 ARCHITECTURE DEFINED")

DERM7PT RESNET-18 BASELINE

Model:
ResNet-18

Input:
(batch, 3, 224, 224)

Output:
(batch, 2)

Parameters:
11,177,538

Model device:
cuda:0
✅ RESNET-18 ARCHITECTURE DEFINED

In [16]:
# DERM7PT RESNET-18 GPU FORWARD PASS TEST
# Purpose: Verify that ResNet-18 correctly processes a real
#          Derm7pt batch and produces two-class predictions.

import torch


model.eval()


images, labels = next(
    iter(train_loader)
)


images = images.to(
    DEVICE,
    non_blocking=True
)

labels = labels.to(
    DEVICE,
    non_blocking=True
)


with torch.no_grad():

    outputs = model(
        images
    )


print("DERM7PT RESNET-18 GPU FORWARD PASS TEST")

print("\nInput image shape:")
print(tuple(images.shape))

print("\nGround-truth label shape:")
print(tuple(labels.shape))

print("\nModel output shape:")
print(tuple(outputs.shape))

print("\nModel device:")
print(next(model.parameters()).device)

print("\nOutput dtype:")
print(outputs.dtype)

print("\nOutput value range:")

print(
    "Minimum:",
    outputs.min().item()
)

print(
    "Maximum:",
    outputs.max().item()
)


if outputs.shape == (images.shape[0], 2):
    print(
        "✅ RESNET-18 GPU FORWARD PASS TEST PASSED"
    )
else:
    print(
        "❌ RESNET-18 FORWARD PASS FAILED"
    )

DERM7PT RESNET-18 GPU FORWARD PASS TEST

Input image shape:
(32, 3, 224, 224)

Ground-truth label shape:
(32,)

Model output shape:
(32, 2)

Model device:
cuda:0

Output dtype:
torch.float32

Output value range:
Minimum: -0.5199184417724609
Maximum: 4.259067535400391
✅ RESNET-18 GPU FORWARD PASS TEST PASSED

In [17]:
# DERM7PT CLASS-WEIGHTED CLASSIFICATION LOSS
# Purpose: Calculate training-set class weights and define the
#          weighted CrossEntropyLoss for melanoma classification.
import torch
import torch.nn as nn


class_counts = (
    train_df["binary_label"]
    .value_counts()
)


non_melanoma_count = int(
    class_counts.get(
        "Non-Melanoma",
        0
    )
)

melanoma_count = int(
    class_counts.get(
        "Melanoma",
        0
    )
)


total_samples = (
    non_melanoma_count
    + melanoma_count
)


class_weight_non_melanoma = (
    total_samples
    / (2 * non_melanoma_count)
)

class_weight_melanoma = (
    total_samples
    / (2 * melanoma_count)
)


class_weights = torch.tensor(
    [
        class_weight_non_melanoma,
        class_weight_melanoma
    ],
    dtype=torch.float32,
    device=DEVICE
)


criterion = nn.CrossEntropyLoss(
    weight=class_weights
)


print("DERM7PT CLASS-WEIGHTED CLASSIFICATION LOSS")

print("\nTraining samples:")
print(total_samples)

print("\nNon-Melanoma:")
print(non_melanoma_count)

print("\nMelanoma:")
print(melanoma_count)

print("\nClass weights:")
print(
    class_weights.detach()
    .cpu()
    .numpy()
)

print("\nLoss:")
print("Weighted CrossEntropyLoss")

print("\nLoss device:")
print(class_weights.device)

print("✅ CLASS-WEIGHTED LOSS READY")

DERM7PT CLASS-WEIGHTED CLASSIFICATION LOSS

Training samples:
413

Non-Melanoma:
323

Melanoma:
90

Class weights:
[0.6393189 2.2944446]

Loss:
Weighted CrossEntropyLoss

Loss device:
cuda:0
✅ CLASS-WEIGHTED LOSS READY

In [18]:
# DERM7PT RESNET-18 SINGLE-BATCH TRAINING TEST
# Purpose: Verify one complete forward, loss, backward, and
#          optimizer-update step on the T4 GPU.

import time
import torch
import torch.optim as optim


optimizer = optim.Adam(
    model.parameters(),
    lr=1e-4,
    weight_decay=1e-5
)


model.train()


images, labels = next(
    iter(train_loader)
)


images = images.to(
    DEVICE,
    non_blocking=True
)

labels = labels.to(
    DEVICE,
    non_blocking=True
)


if torch.cuda.is_available():
    torch.cuda.synchronize()

start_time = time.time()


optimizer.zero_grad(
    set_to_none=True
)


outputs = model(
    images
)


loss = criterion(
    outputs,
    labels
)


loss.backward()


optimizer.step()


if torch.cuda.is_available():
    torch.cuda.synchronize()

elapsed_time = (
    time.time() - start_time
)


predictions = torch.argmax(
    outputs,
    dim=1
)


accuracy = (
    predictions == labels
).float().mean().item()


print("DERM7PT RESNET-18 SINGLE-BATCH TRAINING TEST")

print("\nBatch image shape:")
print(tuple(images.shape))

print("\nBatch label shape:")
print(tuple(labels.shape))

print("\nOutput shape:")
print(tuple(outputs.shape))

print("\nLoss:")
print(f"{loss.item():.6f}")

print("\nBatch accuracy:")
print(f"{accuracy:.6f}")

print("\nTraining step time:")
print(f"{elapsed_time:.2f} seconds")

print("\nGPU memory allocated:")
print(
    f"{torch.cuda.memory_allocated() / (1024 ** 3):.2f} GB"
)

print("✅ SINGLE-BATCH TRAINING TEST PASSED")

DERM7PT RESNET-18 SINGLE-BATCH TRAINING TEST

Batch image shape:
(32, 3, 224, 224)

Batch label shape:
(32,)

Output shape:
(32, 2)

Loss:
0.715735

Batch accuracy:
0.500000

Training step time:
0.50 seconds

GPU memory allocated:
0.22 GB
✅ SINGLE-BATCH TRAINING TEST PASSED

In [19]:
# DERM7PT RESNET-18 FINAL TRAINING CONFIGURATION
# Purpose: Define the reproducible training configuration and
#          artifact paths for the Derm7pt baseline experiment.

import os


EPOCHS = 20
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-5
BATCH_SIZE = 32


BEST_MODEL_PATH = (
    "/kaggle/working/derm7pt_resnet18_best.pth"
)

TRAINING_HISTORY_PATH = (
    "/kaggle/working/derm7pt_resnet18_training_history.pt"
)

FINAL_RESULTS_PATH = (
    "/kaggle/working/derm7pt_resnet18_final_results.json"
)


print("=" * 60)
print("DERM7PT RESNET-18 FINAL TRAINING CONFIGURATION")
print("=" * 60)

print("\nModel:")
print("ResNet-18")

print("\nOptimizer:")
print("Adam")

print("\nLearning rate:")
print(LEARNING_RATE)

print("\nWeight decay:")
print(WEIGHT_DECAY)

print("\nEpochs:")
print(EPOCHS)

print("\nBatch size:")
print(BATCH_SIZE)

print("\nDevice:")
print(DEVICE)

print("\nGPU count:")
print(torch.cuda.device_count())

print("\nMixed precision:")
print("Enabled")

print("\nLoss:")
print("Weighted CrossEntropyLoss")

print("\nPrimary classification metrics:")
print("Accuracy")
print("Precision")
print("Recall")
print("F1")
print("ROC-AUC")

print("\nBest model path:")
print(BEST_MODEL_PATH)

print("\nTraining history path:")
print(TRAINING_HISTORY_PATH)

print("\nFinal results path:")
print(FINAL_RESULTS_PATH)

print("✅ FINAL TRAINING CONFIGURATION READY")

============================================================
DERM7PT RESNET-18 FINAL TRAINING CONFIGURATION
============================================================

Model:
ResNet-18

Optimizer:
Adam

Learning rate:
0.0001

Weight decay:
1e-05

Epochs:
20

Batch size:
32

Device:
cuda

GPU count:
2

Mixed precision:
Enabled

Loss:
Weighted CrossEntropyLoss

Primary classification metrics:
Accuracy
Precision
Recall
F1
ROC-AUC

Best model path:
/kaggle/working/derm7pt_resnet18_best.pth

Training history path:
/kaggle/working/derm7pt_resnet18_training_history.pt

Final results path:
/kaggle/working/derm7pt_resnet18_final_results.json
✅ FINAL TRAINING CONFIGURATION READY

In [20]:
# DERM7PT RESNET-18 FINAL MODEL SETUP
# Purpose: Create a fresh ResNet-18, configure the optimizer,
#          class-weighted loss, multi-GPU execution, and AMP.

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision.models import resnet18


model = resnet18(
    weights=None
)

num_features = model.fc.in_features

model.fc = nn.Linear(
    num_features,
    2
)


# Use both available GPUs when possible.
if torch.cuda.device_count() > 1:

    model = nn.DataParallel(
        model
    )


model = model.to(
    DEVICE
)


optimizer = optim.Adam(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY
)


criterion = nn.CrossEntropyLoss(
    weight=class_weights
)


scaler = torch.amp.GradScaler(
    "cuda"
)


parameter_count = sum(
    p.numel()
    for p in model.parameters()
)


print("DERM7PT RESNET-18 FINAL MODEL SETUP")

print("\nModel:")
print("ResNet-18")

print("\nParameters:")
print(f"{parameter_count:,}")

print("\nDevice:")
print(DEVICE)

print("\nGPU count:")
print(torch.cuda.device_count())

print("\nMulti-GPU:")
print(
    isinstance(
        model,
        nn.DataParallel
    )
)

print("\nOptimizer:")
print("Adam")

print("\nLoss:")
print("Weighted CrossEntropyLoss")

print("\nMixed precision:")
print("Enabled")

print("\nAMP scaler:")
print(type(scaler).__name__)

print("✅ FINAL MODEL SETUP READY")

DERM7PT RESNET-18 FINAL MODEL SETUP

Model:
ResNet-18

Parameters:
11,177,538

Device:
cuda

GPU count:
2

Multi-GPU:
True

Optimizer:
Adam

Loss:
Weighted CrossEntropyLoss

Mixed precision:
Enabled

AMP scaler:
GradScaler
✅ FINAL MODEL SETUP READY

In [21]:
# DERM7PT FINAL AMP + MULTI-GPU TRAINING TEST
# Purpose: Verify one complete mixed-precision, multi-GPU training
#          step before launching the full 20-epoch experiment.

import time
import torch


model.train()


images, labels = next(
    iter(train_loader)
)


images = images.to(
    DEVICE,
    non_blocking=True
)

labels = labels.to(
    DEVICE,
    non_blocking=True
)


optimizer.zero_grad(
    set_to_none=True
)


if torch.cuda.is_available():
    torch.cuda.synchronize()

start_time = time.time()


with torch.amp.autocast(
    device_type="cuda"
):

    outputs = model(
        images
    )

    loss = criterion(
        outputs,
        labels
    )


scaler.scale(
    loss
).backward()


scaler.step(
    optimizer
)

scaler.update()


if torch.cuda.is_available():
    torch.cuda.synchronize()

elapsed_time = (
    time.time() - start_time
)


predictions = torch.argmax(
    outputs,
    dim=1
)


accuracy = (
    predictions == labels
).float().mean().item()


print("DERM7PT FINAL AMP + MULTI-GPU TRAINING TEST")

print("\nBatch image shape:")
print(tuple(images.shape))

print("\nBatch label shape:")
print(tuple(labels.shape))

print("\nOutput shape:")
print(tuple(outputs.shape))

print("\nLoss:")
print(f"{loss.item():.6f}")

print("\nBatch accuracy:")
print(f"{accuracy:.6f}")

print("\nTraining step time:")
print(f"{elapsed_time:.2f} seconds")

print("\nGPU memory allocated:")
print(
    f"{torch.cuda.memory_allocated() / (1024 ** 3):.2f} GB"
)

print("\nMulti-GPU:")
print(
    isinstance(
        model,
        torch.nn.DataParallel
    )
)

print("\nMixed precision:")
print("Enabled")



if (
    outputs.shape == (images.shape[0], 2)
    and isinstance(model, torch.nn.DataParallel)
):

    print(
        "✅ FINAL TRAINING STEP TEST PASSED"
    )

else:

    print(
        "❌ FINAL TRAINING STEP TEST FAILED"
    )

DERM7PT FINAL AMP + MULTI-GPU TRAINING TEST

Batch image shape:
(32, 3, 224, 224)

Batch label shape:
(32,)

Output shape:
(32, 2)

Loss:
0.743718

Batch accuracy:
0.218750

Training step time:
1.19 seconds

GPU memory allocated:
0.23 GB

Multi-GPU:
True

Mixed precision:
Enabled
✅ FINAL TRAINING STEP TEST PASSED

In [22]:
# DERM7PT RESNET-18 CLEAN BASELINE INITIALIZATION
# Purpose: Reinitialize the model and all training components
#          so the recorded 20-epoch baseline starts from scratch.

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision.models import resnet18


model = resnet18(
    weights=None
)

num_features = model.fc.in_features

model.fc = nn.Linear(
    num_features,
    2
)


if torch.cuda.device_count() > 1:

    model = nn.DataParallel(
        model
    )


model = model.to(
    DEVICE
)


optimizer = optim.Adam(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY
)


criterion = nn.CrossEntropyLoss(
    weight=class_weights
)


scaler = torch.amp.GradScaler(
    "cuda"
)


parameter_count = sum(
    p.numel()
    for p in model.parameters()
)


print("DERM7PT RESNET-18 CLEAN BASELINE INITIALIZATION")

print("\nModel:")
print("ResNet-18")

print("\nParameters:")
print(f"{parameter_count:,}")

print("\nDevice:")
print(DEVICE)

print("\nGPU count:")
print(torch.cuda.device_count())

print("\nMulti-GPU:")
print(
    isinstance(
        model,
        nn.DataParallel
    )
)

print("\nMixed precision:")
print("Enabled")

print("\nOptimizer:")
print("Adam")

print("\nLoss:")
print("Weighted CrossEntropyLoss")

print("\nTraining state:")
print("FRESH INITIALIZATION")

print("✅ CLEAN BASELINE READY FOR TRAINING")

DERM7PT RESNET-18 CLEAN BASELINE INITIALIZATION

Model:
ResNet-18

Parameters:
11,177,538

Device:
cuda

GPU count:
2

Multi-GPU:
True

Mixed precision:
Enabled

Optimizer:
Adam

Loss:
Weighted CrossEntropyLoss

Training state:
FRESH INITIALIZATION
✅ CLEAN BASELINE READY FOR TRAINING

In [23]:
# DERM7PT RESNET-18 BASELINE TRAINING
# Purpose: Train the clean Derm7pt ResNet-18 baseline for 20
#          epochs with validation metrics and best-checkpoint saving.

import os
import time
import json
import numpy as np
import torch
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)


history = {
    "train_loss": [],
    "val_loss": [],
    "val_accuracy": [],
    "val_precision": [],
    "val_recall": [],
    "val_f1": [],
    "val_roc_auc": []
}


best_f1 = -1.0
best_epoch = 0


def evaluate_model(model, loader):

    model.eval()

    total_loss = 0.0
    all_labels = []
    all_predictions = []
    all_probabilities = []

    with torch.no_grad():

        for images, labels in loader:

            images = images.to(
                DEVICE,
                non_blocking=True
            )

            labels = labels.to(
                DEVICE,
                non_blocking=True
            )

            with torch.amp.autocast(
                device_type="cuda"
            ):

                outputs = model(
                    images
                )

                loss = criterion(
                    outputs,
                    labels
                )

            probabilities = torch.softmax(
                outputs.float(),
                dim=1
            )[:, 1]

            predictions = torch.argmax(
                outputs,
                dim=1
            )

            total_loss += (
                loss.item()
                * images.size(0)
            )

            all_labels.extend(
                labels.cpu().numpy()
            )

            all_predictions.extend(
                predictions.cpu().numpy()
            )

            all_probabilities.extend(
                probabilities.cpu().numpy()
            )


    all_labels = np.array(
        all_labels
    )

    all_predictions = np.array(
        all_predictions
    )

    all_probabilities = np.array(
        all_probabilities
    )


    average_loss = (
        total_loss
        / len(loader.dataset)
    )


    accuracy = accuracy_score(
        all_labels,
        all_predictions
    )

    precision = precision_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    recall = recall_score(
        all_labels,
        all_predictions,
        zero_division=0
    )

    f1 = f1_score(
        all_labels,
        all_predictions,
        zero_division=0
    )


    try:

        roc_auc = roc_auc_score(
            all_labels,
            all_probabilities
        )

    except ValueError:

        roc_auc = float("nan")


    return (
        average_loss,
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    )


print("DERM7PT RESNET-18 BASELINE TRAINING")

print(
    f"\nTraining for {EPOCHS} epochs..."
)

training_start = time.time()


for epoch in range(
    1,
    EPOCHS + 1
):

    epoch_start = time.time()

    model.train()

    running_loss = 0.0


    for images, labels in train_loader:

        images = images.to(
            DEVICE,
            non_blocking=True
        )

        labels = labels.to(
            DEVICE,
            non_blocking=True
        )


        optimizer.zero_grad(
            set_to_none=True
        )


        with torch.amp.autocast(
            device_type="cuda"
        ):

            outputs = model(
                images
            )

            loss = criterion(
                outputs,
                labels
            )


        scaler.scale(
            loss
        ).backward()


        scaler.step(
            optimizer
        )

        scaler.update()


        running_loss += (
            loss.item()
            * images.size(0)
        )


    train_loss = (
        running_loss
        / len(train_loader.dataset)
    )


    (
        val_loss,
        val_accuracy,
        val_precision,
        val_recall,
        val_f1,
        val_roc_auc
    ) = evaluate_model(
        model,
        val_loader
    )


    history["train_loss"].append(
        train_loss
    )

    history["val_loss"].append(
        val_loss
    )

    history["val_accuracy"].append(
        val_accuracy
    )

    history["val_precision"].append(
        val_precision
    )

    history["val_recall"].append(
        val_recall
    )

    history["val_f1"].append(
        val_f1
    )

    history["val_roc_auc"].append(
        val_roc_auc
    )


    epoch_time = (
        time.time()
        - epoch_start
    )


    is_best = (
        val_f1 > best_f1
    )


    if is_best:

        best_f1 = val_f1
        best_epoch = epoch

        torch.save(
            model.state_dict(),
            BEST_MODEL_PATH
        )


    marker = (
        " ⭐ BEST"
        if is_best
        else ""
    )


    print(
        f"Epoch {epoch:02d}/{EPOCHS} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f} | "
        f"Val Acc: {val_accuracy:.4f} | "
        f"Val Precision: {val_precision:.4f} | "
        f"Val Recall: {val_recall:.4f} | "
        f"Val F1: {val_f1:.4f} | "
        f"Val AUC: {val_roc_auc:.4f} | "
        f"Time: {epoch_time / 60:.2f} min"
        f"{marker}"
    )


total_training_time = (
    time.time()
    - training_start
)


torch.save(
    history,
    TRAINING_HISTORY_PATH
)


print("DERM7PT RESNET-18 BASELINE TRAINING COMPLETED")
print("=" * 60)

print("\nBest validation F1:")
print(f"{best_f1:.6f}")

print("\nBest epoch:")
print(best_epoch)

print("\nBest model:")
print(BEST_MODEL_PATH)

print("\nTraining history:")
print(TRAINING_HISTORY_PATH)

print("\nTotal training time:")
print(
    f"{total_training_time / 60:.2f} minutes"
)

DERM7PT RESNET-18 BASELINE TRAINING

Training for 20 epochs...
Epoch 01/20 | Train Loss: 0.7047 | Val Loss: 0.6082 | Val Acc: 0.7192 | Val Precision: 0.7000 | Val Recall: 0.1148 | Val F1: 0.1972 | Val AUC: 0.6206 | Time: 0.11 min ⭐ BEST
Epoch 02/20 | Train Loss: 0.6220 | Val Loss: 0.5917 | Val Acc: 0.7143 | Val Precision: 0.5205 | Val Recall: 0.6230 | Val F1: 0.5672 | Val AUC: 0.7372 | Time: 0.09 min ⭐ BEST
Epoch 03/20 | Train Loss: 0.6233 | Val Loss: 0.5433 | Val Acc: 0.7143 | Val Precision: 0.7143 | Val Recall: 0.0820 | Val F1: 0.1471 | Val AUC: 0.7605 | Time: 0.09 min
Epoch 04/20 | Train Loss: 0.6092 | Val Loss: 0.5535 | Val Acc: 0.7340 | Val Precision: 0.5538 | Val Recall: 0.5902 | Val F1: 0.5714 | Val AUC: 0.7663 | Time: 0.09 min ⭐ BEST
Epoch 05/20 | Train Loss: 0.5832 | Val Loss: 0.5980 | Val Acc: 0.7094 | Val Precision: 0.5111 | Val Recall: 0.7541 | Val F1: 0.6093 | Val AUC: 0.7922 | Time: 0.09 min ⭐ BEST
Epoch 06/20 | Train Loss: 0.5924 | Val Loss: 0.5617 | Val Acc: 0.7094 | Val Precision: 0.5185 | Val Recall: 0.4590 | Val F1: 0.4870 | Val AUC: 0.7240 | Time: 0.09 min
Epoch 07/20 | Train Loss: 0.5387 | Val Loss: 0.5729 | Val Acc: 0.7094 | Val Precision: 0.5122 | Val Recall: 0.6885 | Val F1: 0.5874 | Val AUC: 0.7730 | Time: 0.10 min
Epoch 08/20 | Train Loss: 0.5502 | Val Loss: 0.5726 | Val Acc: 0.7192 | Val Precision: 0.5303 | Val Recall: 0.5738 | Val F1: 0.5512 | Val AUC: 0.7405 | Time: 0.09 min
Epoch 09/20 | Train Loss: 0.5555 | Val Loss: 0.6721 | Val Acc: 0.6207 | Val Precision: 0.4200 | Val Recall: 0.6885 | Val F1: 0.5217 | Val AUC: 0.6951 | Time: 0.09 min
Epoch 10/20 | Train Loss: 0.5130 | Val Loss: 0.5500 | Val Acc: 0.7488 | Val Precision: 0.5676 | Val Recall: 0.6885 | Val F1: 0.6222 | Val AUC: 0.7800 | Time: 0.09 min ⭐ BEST
Epoch 11/20 | Train Loss: 0.4904 | Val Loss: 0.6103 | Val Acc: 0.7340 | Val Precision: 0.5686 | Val Recall: 0.4754 | Val F1: 0.5179 | Val AUC: 0.7074 | Time: 0.08 min
Epoch 12/20 | Train Loss: 0.4762 | Val Loss: 0.6713 | Val Acc: 0.7241 | Val Precision: 0.5424 | Val Recall: 0.5246 | Val F1: 0.5333 | Val AUC: 0.7107 | Time: 0.09 min
Epoch 13/20 | Train Loss: 0.5292 | Val Loss: 0.5934 | Val Acc: 0.7143 | Val Precision: 0.5190 | Val Recall: 0.6721 | Val F1: 0.5857 | Val AUC: 0.7636 | Time: 0.09 min
Epoch 14/20 | Train Loss: 0.4338 | Val Loss: 0.5761 | Val Acc: 0.6995 | Val Precision: 0.5000 | Val Recall: 0.4262 | Val F1: 0.4602 | Val AUC: 0.7348 | Time: 0.10 min
Epoch 15/20 | Train Loss: 0.4342 | Val Loss: 0.8230 | Val Acc: 0.6305 | Val Precision: 0.4314 | Val Recall: 0.7213 | Val F1: 0.5399 | Val AUC: 0.7024 | Time: 0.09 min
Epoch 16/20 | Train Loss: 0.4260 | Val Loss: 0.9611 | Val Acc: 0.6207 | Val Precision: 0.4259 | Val Recall: 0.7541 | Val F1: 0.5444 | Val AUC: 0.7553 | Time: 0.10 min
Epoch 17/20 | Train Loss: 0.4388 | Val Loss: 1.0206 | Val Acc: 0.5517 | Val Precision: 0.3770 | Val Recall: 0.7541 | Val F1: 0.5027 | Val AUC: 0.6503 | Time: 0.10 min
Epoch 18/20 | Train Loss: 0.4743 | Val Loss: 0.7040 | Val Acc: 0.7340 | Val Precision: 0.5714 | Val Recall: 0.4590 | Val F1: 0.5091 | Val AUC: 0.7028 | Time: 0.10 min
Epoch 19/20 | Train Loss: 0.4131 | Val Loss: 0.6518 | Val Acc: 0.7389 | Val Precision: 0.5870 | Val Recall: 0.4426 | Val F1: 0.5047 | Val AUC: 0.7393 | Time: 0.10 min
Epoch 20/20 | Train Loss: 0.3707 | Val Loss: 0.8743 | Val Acc: 0.6355 | Val Precision: 0.4343 | Val Recall: 0.7049 | Val F1: 0.5375 | Val AUC: 0.7341 | Time: 0.09 min
DERM7PT RESNET-18 BASELINE TRAINING COMPLETED
============================================================

Best validation F1:
0.622222

Best epoch:
10

Best model:
/kaggle/working/derm7pt_resnet18_best.pth

Training history:
/kaggle/working/derm7pt_resnet18_training_history.pt

Total training time:
1.86 minutes

In [24]:
# DERM7PT RESNET-18 BASELINE RESULTS SAVE
# Purpose: Permanently record the best validation performance
#          and training configuration before final test evaluation.

import json
import os


baseline_results = {
    "dataset": "Derm7pt",
    "task": "Binary Classification",
    "input_modality": "Dermoscopic",
    "model": "ResNet-18",

    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "learning_rate": LEARNING_RATE,
    "weight_decay": WEIGHT_DECAY,

    "loss": "Weighted CrossEntropyLoss",
    "optimizer": "Adam",
    "mixed_precision": True,
    "multi_gpu": True,

    "best_epoch": best_epoch,

    "best_validation_f1": history["val_f1"][best_epoch - 1],
    "validation_accuracy_at_best": history["val_accuracy"][best_epoch - 1],
    "validation_precision_at_best": history["val_precision"][best_epoch - 1],
    "validation_recall_at_best": history["val_recall"][best_epoch - 1],
    "validation_roc_auc_at_best": history["val_roc_auc"][best_epoch - 1],
    "validation_loss_at_best": history["val_loss"][best_epoch - 1],

    "best_model_path": BEST_MODEL_PATH,
    "training_history_path": TRAINING_HISTORY_PATH
}


with open(
    "/kaggle/working/derm7pt_resnet18_baseline_results.json",
    "w"
) as f:

    json.dump(
        baseline_results,
        f,
        indent=4
    )


RESULTS_PATH = (
    "/kaggle/working/"
    "derm7pt_resnet18_baseline_results.json"
)


print("DERM7PT RESNET-18 BASELINE RESULTS SAVED")

print("\nResults file:")
print(RESULTS_PATH)

print("\nBest epoch:")
print(best_epoch)

print("\nBest validation F1:")
print(
    f"{baseline_results['best_validation_f1']:.6f}"
)

print("\nValidation Accuracy:")
print(
    f"{baseline_results['validation_accuracy_at_best']:.6f}"
)

print("\nValidation Precision:")
print(
    f"{baseline_results['validation_precision_at_best']:.6f}"
)

print("\nValidation Recall:")
print(
    f"{baseline_results['validation_recall_at_best']:.6f}"
)

print("\nValidation ROC-AUC:")
print(
    f"{baseline_results['validation_roc_auc_at_best']:.6f}"
)

print("✅ BASELINE RESULTS SAFELY RECORDED")

DERM7PT RESNET-18 BASELINE RESULTS SAVED

Results file:
/kaggle/working/derm7pt_resnet18_baseline_results.json

Best epoch:
10

Best validation F1:
0.622222

Validation Accuracy:
0.748768

Validation Precision:
0.567568

Validation Recall:
0.688525

Validation ROC-AUC:
0.780016
✅ BASELINE RESULTS SAFELY RECORDED

In [25]:
# DERM7PT RESNET-18 BASELINE ARTIFACT VERIFICATION
# Purpose: Verify that the trained checkpoint, training history,
#          and baseline results are safely stored before testing.

import os


ARTIFACTS = {
    "Best model": BEST_MODEL_PATH,
    "Training history": TRAINING_HISTORY_PATH,
    "Baseline results": RESULTS_PATH
}


print("DERM7PT RESNET-18 BASELINE ARTIFACT VERIFICATION")


all_verified = True


for name, path in ARTIFACTS.items():

    exists = os.path.exists(path)

    print(f"\n{name}:")
    print(path)

    print("Exists:")
    print(exists)

    if exists:

        size_mb = (
            os.path.getsize(path)
            / (1024 ** 2)
        )

        print(
            f"Size: {size_mb:.2f} MB"
        )

    else:

        all_verified = False



if all_verified:

    print(
        "✅ ALL BASELINE ARTIFACTS VERIFIED"
    )

else:

    print(
        "❌ SOME BASELINE ARTIFACTS ARE MISSING"
    )

DERM7PT RESNET-18 BASELINE ARTIFACT VERIFICATION

Best model:
/kaggle/working/derm7pt_resnet18_best.pth
Exists:
True
Size: 42.72 MB

Training history:
/kaggle/working/derm7pt_resnet18_training_history.pt
Exists:
True
Size: 0.00 MB

Baseline results:
/kaggle/working/derm7pt_resnet18_baseline_results.json
Exists:
True
Size: 0.00 MB
✅ ALL BASELINE ARTIFACTS VERIFIED

In [26]:
# DERM7PT BEST RESNET-18 CHECKPOINT LOADING
# Purpose: Load the saved best-validation checkpoint into a
#          fresh ResNet-18 before final test-set evaluation.

import torch
import torch.nn as nn
from torchvision.models import resnet18


best_model = resnet18(
    weights=None
)

num_features = best_model.fc.in_features

best_model.fc = nn.Linear(
    num_features,
    2
)


if torch.cuda.device_count() > 1:

    best_model = nn.DataParallel(
        best_model
    )


best_model = best_model.to(
    DEVICE
)


checkpoint = torch.load(
    BEST_MODEL_PATH,
    map_location=DEVICE,
    weights_only=True
)


best_model.load_state_dict(
    checkpoint
)


best_model.eval()


print("DERM7PT BEST RESNET-18 CHECKPOINT LOADING")

print("\nCheckpoint:")
print(BEST_MODEL_PATH)

print("\nBest epoch:")
print(best_epoch)

print("\nModel parameters:")
print(
    f"{sum(p.numel() for p in best_model.parameters()):,}"
)

print("\nDevice:")
print(
    next(best_model.parameters()).device
)

print("\nMulti-GPU:")
print(
    isinstance(
        best_model,
        nn.DataParallel
    )
)

print("\nModel mode:")
print(
    "Evaluation"
    if not best_model.training
    else "Training"
)

print("✅ BEST CHECKPOINT LOADED")

DERM7PT BEST RESNET-18 CHECKPOINT LOADING

Checkpoint:
/kaggle/working/derm7pt_resnet18_best.pth

Best epoch:
10

Model parameters:
11,177,538

Device:
cuda:0

Multi-GPU:
True

Model mode:
Evaluation
✅ BEST CHECKPOINT LOADED

In [27]:
# DERM7PT RESNET-18 FINAL TEST SET EVALUATION
# Purpose: Evaluate the saved best checkpoint on the untouched
#          Derm7pt test set and calculate research metrics.

import time
import numpy as np
import torch
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)


best_model.eval()


all_labels = []
all_predictions = []
all_probabilities = []

total_test_loss = 0.0


if torch.cuda.is_available():
    torch.cuda.synchronize()

evaluation_start = time.time()


with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(
            DEVICE,
            non_blocking=True
        )

        labels = labels.to(
            DEVICE,
            non_blocking=True
        )


        with torch.amp.autocast(
            device_type="cuda"
        ):

            outputs = best_model(
                images
            )

            loss = criterion(
                outputs,
                labels
            )


        probabilities = torch.softmax(
            outputs.float(),
            dim=1
        )[:, 1]


        predictions = torch.argmax(
            outputs,
            dim=1
        )


        total_test_loss += (
            loss.item()
            * images.size(0)
        )


        all_labels.extend(
            labels.cpu().numpy()
        )

        all_predictions.extend(
            predictions.cpu().numpy()
        )

        all_probabilities.extend(
            probabilities.cpu().numpy()
        )


if torch.cuda.is_available():
    torch.cuda.synchronize()


evaluation_time = (
    time.time()
    - evaluation_start
)


all_labels = np.array(
    all_labels
)

all_predictions = np.array(
    all_predictions
)

all_probabilities = np.array(
    all_probabilities
)


test_loss = (
    total_test_loss
    / len(test_loader.dataset)
)


test_accuracy = accuracy_score(
    all_labels,
    all_predictions
)

test_precision = precision_score(
    all_labels,
    all_predictions,
    zero_division=0
)

test_recall = recall_score(
    all_labels,
    all_predictions,
    zero_division=0
)

test_f1 = f1_score(
    all_labels,
    all_predictions,
    zero_division=0
)

test_roc_auc = roc_auc_score(
    all_labels,
    all_probabilities
)


cm = confusion_matrix(
    all_labels,
    all_predictions
)


average_time_per_image = (
    evaluation_time
    / len(test_loader.dataset)
)


print("DERM7PT RESNET-18 FINAL TEST SET EVALUATION")

print("\nTest samples:")
print(len(test_loader.dataset))

print("\nTest loss:")
print(f"{test_loss:.6f}")

print("\nTest Accuracy:")
print(f"{test_accuracy:.6f}")

print("\nTest Precision:")
print(f"{test_precision:.6f}")

print("\nTest Recall / Sensitivity:")
print(f"{test_recall:.6f}")

print("\nTest F1:")
print(f"{test_f1:.6f}")

print("\nTest ROC-AUC:")
print(f"{test_roc_auc:.6f}")

print("\nConfusion Matrix:")
print(cm)

print("\nTotal evaluation time:")
print(f"{evaluation_time / 60:.2f} minutes")

print("\nAverage time per test image:")
print(f"{average_time_per_image:.4f} seconds")

print("✅ DERM7PT TEST EVALUATION COMPLETED")

DERM7PT RESNET-18 FINAL TEST SET EVALUATION

Test samples:
395

Test loss:
0.538641

Test Accuracy:
0.746835

Test Precision:
0.503817

Test Recall / Sensitivity:
0.653465

Test F1:
0.568966

Test ROC-AUC:
0.789048

Confusion Matrix:
[[229  65]
 [ 35  66]]

Total evaluation time:
0.06 minutes

Average time per test image:
0.0087 seconds
✅ DERM7PT TEST EVALUATION COMPLETED

In [28]:
# 
# DERM7PT RESNET-18 FINAL RESULTS SAVE
# Purpose: Permanently record the untouched test-set performance
#          of the best-validation ResNet-18 checkpoint.

import json


final_results = {
    "dataset": "Derm7pt",
    "task": "Binary Classification",
    "input_modality": "Dermoscopic",
    "model": "ResNet-18",

    "best_epoch": best_epoch,

    "test_samples": len(test_loader.dataset),

    "test_loss": test_loss,
    "test_accuracy": test_accuracy,
    "test_precision": test_precision,
    "test_recall": test_recall,
    "test_f1": test_f1,
    "test_roc_auc": test_roc_auc,

    "confusion_matrix": cm.tolist(),

    "evaluation_time_seconds": evaluation_time,
    "average_time_per_test_image_seconds": average_time_per_image,

    "best_model_path": BEST_MODEL_PATH,
    "training_history_path": TRAINING_HISTORY_PATH,
    "baseline_results_path": RESULTS_PATH
}


FINAL_RESULTS_PATH = (
    "/kaggle/working/"
    "derm7pt_resnet18_final_results.json"
)


with open(
    FINAL_RESULTS_PATH,
    "w"
) as f:

    json.dump(
        final_results,
        f,
        indent=4
    )


print("DERM7PT RESNET-18 FINAL RESULTS SAVED")

print("\nFinal results file:")
print(FINAL_RESULTS_PATH)

print("\nTest Accuracy:")
print(f"{test_accuracy:.6f}")

print("\nTest Precision:")
print(f"{test_precision:.6f}")

print("\nTest Recall:")
print(f"{test_recall:.6f}")

print("\nTest F1:")
print(f"{test_f1:.6f}")

print("\nTest ROC-AUC:")
print(f"{test_roc_auc:.6f}")

print("✅ FINAL TEST RESULTS SAFELY RECORDED")

DERM7PT RESNET-18 FINAL RESULTS SAVED

Final results file:
/kaggle/working/derm7pt_resnet18_final_results.json

Test Accuracy:
0.746835

Test Precision:
0.503817

Test Recall:
0.653465

Test F1:
0.568966

Test ROC-AUC:
0.789048
✅ FINAL TEST RESULTS SAFELY RECORDED

In [29]:
# DERM7PT RESNET-18 FINAL ARTIFACT VERIFICATION
# Purpose: Verify the trained checkpoint, training history,
#          baseline results, and final test results.

import os


FINAL_ARTIFACTS = {
    "Best model": BEST_MODEL_PATH,
    "Training history": TRAINING_HISTORY_PATH,
    "Baseline results": RESULTS_PATH,
    "Final results": FINAL_RESULTS_PATH
}


print("DERM7PT RESNET-18 FINAL ARTIFACT VERIFICATION")


all_verified = True


for name, path in FINAL_ARTIFACTS.items():

    exists = os.path.exists(path)

    print(f"\n{name}:")
    print(path)

    print("Exists:")
    print(exists)

    if exists:

        size_mb = (
            os.path.getsize(path)
            / (1024 ** 2)
        )

        print(
            f"Size: {size_mb:.2f} MB"
        )

    else:

        all_verified = False



if all_verified:

    print(
        "✅ ALL DERM7PT RESNET-18 ARTIFACTS VERIFIED"
    )

else:

    print(
        "❌ SOME ARTIFACTS ARE MISSING"
    )

DERM7PT RESNET-18 FINAL ARTIFACT VERIFICATION

Best model:
/kaggle/working/derm7pt_resnet18_best.pth
Exists:
True
Size: 42.72 MB

Training history:
/kaggle/working/derm7pt_resnet18_training_history.pt
Exists:
True
Size: 0.00 MB

Baseline results:
/kaggle/working/derm7pt_resnet18_baseline_results.json
Exists:
True
Size: 0.00 MB

Final results:
/kaggle/working/derm7pt_resnet18_final_results.json
Exists:
True
Size: 0.00 MB
✅ ALL DERM7PT RESNET-18 ARTIFACTS VERIFIED

In [30]:
# DERM7PT RESNET-18 BASELINE BACKUP
# Purpose: Create one portable backup containing all important
#          ResNet-18 training and evaluation artifacts.

import os
import zipfile


BACKUP_PATH = (
    "/kaggle/working/"
    "Derm7pt_ResNet18_Baseline_Backup.zip"
)


ARTIFACT_PATHS = [
    BEST_MODEL_PATH,
    TRAINING_HISTORY_PATH,
    RESULTS_PATH,
    FINAL_RESULTS_PATH
]


print("DERM7PT RESNET-18 BASELINE BACKUP")


with zipfile.ZipFile(
    BACKUP_PATH,
    "w",
    compression=zipfile.ZIP_DEFLATED,
    compresslevel=1
) as backup:

    for path in ARTIFACT_PATHS:

        if not os.path.exists(path):
            raise FileNotFoundError(
                f"Missing artifact: {path}"
            )

        backup.write(
            path,
            arcname=os.path.basename(path)
        )


print("\nBackup file:")
print(BACKUP_PATH)

print("\nBackup size:")
print(
    f"{os.path.getsize(BACKUP_PATH) / (1024 ** 3):.2f} GB"
)

print("\nIncluded artifacts:")

for path in ARTIFACT_PATHS:
    print(
        f"  ✓ {os.path.basename(path)}"
    )


print("✅ DERM7PT RESNET-18 BACKUP READY")

DERM7PT RESNET-18 BASELINE BACKUP

Backup file:
/kaggle/working/Derm7pt_ResNet18_Baseline_Backup.zip

Backup size:
0.04 GB

Included artifacts:
  ✓ derm7pt_resnet18_best.pth
  ✓ derm7pt_resnet18_training_history.pt
  ✓ derm7pt_resnet18_baseline_results.json
  ✓ derm7pt_resnet18_final_results.json
✅ DERM7PT RESNET-18 BACKUP READY